apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../source
  - ingress.yaml
  - namespace.yaml

namespace: argocd

patches:
- path: deployment-argocd-server.yaml
  target:
    kind: Deployment
    name: argocd-server
