apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
  path: /
spec:
  project: default
  source:
    repoURL: https://github.com/Leo310/HerGinnie-gitops
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: myherginniewebsite

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
