apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgBoAPwHA5RmMx02RgJm+jUhq2KQBBDTzpUxfJde8ARrd+oHZkFxCdBVLeNvMlkddsJ6FloL8BXYLaeoN8hqg9LibFwDQ7leluNGzcC9LQXDphZL89QmW6od/fP/S3lUl14aD8/XSMga+jYGsUgZ92C+G869zZNQdBSvL93UIh7NJA90bAyugIv/0nIYKRrFr4DISs+Otn/Zj/9oUOxcosngnu1hoppL+VY+rqVxR+npKlNluI/deurNmPgmMtvFFhuviqcPOwuJyUXTK7EP6mjk8d/dVQjgEj9XizQCprBClJ58vg1bHZGmuMtxyYyEU0QKB7gfhRfAE9nRm+UV4XLUlXt1ALlmcO/BY6CJZGMVQJVEIlQqpKWyPokPbNAiV7CvP7b9luvg6Kb6/iLeUDlU/Iw8E0v8zU0bKlmrzaL1WQaSuZ75alRB9h4z4ZAhV0fxCj70JAMQgR4gwxIKzcoVwKqo7jXZ0cjzlXETuzFGh2EBFkTQVL807QqrgjdKNbGZXrZW0BiIDiOtCEDnFSm46CVeIHNBtw618Rvf6LMgS/EQWNf31eADNNyjiyDwTPVsRNf2IFKrVapbVv1Mzo6j7AOcH2P9Btdpxzs9U8L3anEMHw/O3Zls1BVCCAPo2LuCZhXidPHog79J/LUJK1CUC1SyaMJF1lf7hR0Af9U3QO5yvJM7nOunnRFuWuwsJoNYyr/MssYh3ffoDL4+b8WVFDTb
    CF_API_TOKEN: AgDMb035DsGjofWwZZ0dYgg1pDnMVBf9/O1qUzfClbDgTpYrUAR/cdvxxon9dGtTcOccFH4ojg45qUNrHt5tXPnyHADqLmJGfKC9K6Eb+VG2c0sIcIqUHDUqXmAgHUZJ+OUL3H6y4U74v/f1eVPkVnn2zLw0uQgI0MKnbIbnIbVxIdojUGpDZFXOmhKjOv0b9Yc3SbojBsU6927KT4suNYeGz4UOwawAHj9wKLH8/z01CWxxOoz/iBN8sPRv0TPSuq22bWVCyWVzjkT54bjg5V6Awof0Swo/w2MC1hKH6vfgMPZuVgdwWlkvM/3QW+DaWTjQFqtJZwXYG6MYV0pTShmxpHpwbBT6NbcUVK5cJp/X/NVU28s3jt//HN9jk8FV08WrDElEwkbO542AusieGNPN+EVq2aSzzcToNsQB1EnrYHO9TVp1pat9Hjy3fSUq/ruNPBUzLkcEDhZ864fCaz3mDIXvpQH1RLYRqOh1iyPUCTf7Et1js9+0qMLFVn3SDwV7+S/TCc+ai7EJXSpOlsELOkAsyAugy3inlG9mpYCZMsP9np/Pcu4ZN/KIq1tqx8Oia9yn2JUfaWFMxaM1Hv6suSt0DnId2c8U6+b62YZxaKhwugLXAMVdl+iLvETznwtnag6PDfbun0i06pX/YGSOVv22FySIWCMwnqsEzFEh/dT38p1tE6iMOWenjIGRqUU03T6tmjBZ3kKSfWJ8NtScfGEohZnS3gJ4vdaArtzAqXNvrY2FMdjw
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

