apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgA8vFVeGnQm+xeh7baYznJP+elLnS3PmZQnJOey54jCqdF00zRRQVvmTzzH2wmr2EYqleiqoRATtuhvB1VFWc77dDgEyo2LXlZWjrnv8+cOyHd5pz5H81lh+EdwCZKfOPsgG1vJtCIJ0dbh7Kar9Dynmpwq/EQrmN3wVUx3JFlHqs9FEQQZVL69zMBGbryRcRyxpURmsgce9LK2utMtLgGJ2sv4gpZQtlmmigwB1pGkOYAacOHMA1RoCnOi8H24k40IEpF8tYKzSbIk9ynk3Ty81KHhIQXrhwhqRP7oVq/e+J8C7eOBFi8Kp/IvQCA4qRuAUcA8cvu0mXx5TgB9VVFkBmi1L8Lf8GYbMUp2eXnIU50dtkBuGS1kRByGArZHPVCO9ho38PuaxG2/W4berXLLlguPThb9A9zWw+OXpWFk8YEPom257lWgE1L2Yi82EmAECgJ6PGuw0icXInY8SoMuzqeeIm6Rw1kR2Or3li85iyIjQFjtK/NQPdtVXcYb+7xCAdlJYlHpdZ/hz9NbyaqsxCx0ag5CFGs15ktGWLlTwdTQr+DJoLjyggEw9MCUev3rNcunlVJLrtjkeDb9rx0TwNG3Mww4KPB0fVtARGsj/QlPQMq2tg245aJBTj6Csnc5ctTLBpVBES1MyhooiVUZlHxhMNPntu+wTzl9IyaPe/jUwkYzZPckz2AFrYzaTAnQ4gmBHW+ROCpMfh0LPOXZ5VpW
    CF_API_TOKEN: AgAXLDoAVWVV+KwXetZ5CeiluKiqYj6ZRbKcabM+iIKO55UJujFL+AoPNW2Uzkc/fienxMGHLo5Ygrp4OtA32ki31wqQeX4SYgTOyxmJtxDfaONY+R3sPMmWzLUrFmNqsNP4S2qHGfu/XQCkd/16C1n59TNSYPPdtrrM+GsMEcKDmJCiUAklKqTSkmUU/uAGJRoC6VfQKRXLL8Ikf4w7MBMV0uiDbr0AUu4W9m4/eiHGxHhlGAelPCPGTEE/FjKYkg7wXG7pZ6uHa/MWxv+bVq4ZsaSXMqbkQnT+3n1TbFFoH7QDfzc8iKjmxo/YybcuIpxgO27XTQbM+2UevjdVclEbv5VuibEhwahigpSVkqenZIdvAZcAG4VaXO5UHp774h7DjcmePejmOzifetnXy1WYqMD9Ku8I4kw8aZGltGP+kBNldHADa6QGoWFnzv5Hgk8KTVaC26rj103s0DKC1Pj7tAZY6BJKcABgLr1fFDxfyrYU0ZPRDbdCTV/2+ZDNh1vif++snXWHSwqKl+ZSSRRThqLNsyr1IL4AQqKCb9joZ4c5fVegV6sAbZioaaLlNS1ivzl8kEWLVQ4xBLYyfGeioMZVxeA8vMj5Hp/p4msEkqAdZjuqalq189j22LFxOdlM+qA/uR5rv1JN6WeqpjA6pNgr3rldQJNy+61aYhaDqvwdDUJizcIkLzOc05aL9YCCVmei+YwkpsQxzqsRu5UZe+y6SUeR36dVeTL8F95Bh58rJKu371wB
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

