apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgB9vKDMH4riiNWwtTSpC+uZGNTOgA0ElPVNwEwTqie9ugC1HEHjW2Z6oB1LHMXGBFvOy5yz616XmEomMspZH079vTliBIyST08AEoLmGtrMw1fILge8KTnVoeJWyAWFOlho76ylYzvjrAFrg2JBPS6vydegFdL6uOWGmFMd7b3xzTajWbZh3YvY9vj5b51V2A5Nko8L8aQtQ/EnXP+jK/tzrHb1j52B5c+yOReDQayUMm1c2GkRysG6LI8OiNlRHdeu60nWASou0qqDAU6aucLP98SHelDf9gnMoKAY7MMCMYClHHtCCXmkHN+xIHLVRv3h2JlcGwyYpftDtG+a4gngpYHrict6kTd7wambNZzGK/LxWh5fmltADlfkbE9VRiY4Uve58DCv2MMkzdSaIjZNyRMiihME90hYhl9B1HapvtVPARyu97oh0ssuiaVhak5vDIAX11m9L0bxgvTbKam2UM/4bUSt0gxoqAN/MZstjhEAQb2EWJr2cOkdK8x0ZDrQqYqVHo6aWOuFgrWZTimD8/jkmA8Th/LDcuQgzhiwqt4+e//IEjB+RXS24X9I+plnCHlpyyCM1eFvqvUYWDGETcLPEVK+yktYtVZRaMYj7fXduzrItAMCJsBip31uGpI9iVemRRnqz5AWa+0CQR8RR0gSVbFZ0ie1jcm0RIccax4W23ODatfRAiZN2iZCMecdsIi6KWiFkHMKLfs4+folTmms
    CF_API_KEY: AgBwmNP7PFKgW8TpKftTHMOtU+vyzGWkzq181QcwOJmkV4QZBFZ2sqIAX/4kLdzWcMaZ+L3siMYU2YSKBh+lqvVn6dMIDxVTGaLQnWZykOR9mLjhCb5QHuETo5BRx4Gd9eIjoV7JgCHgmTaf9E4aF/IoSvJXur/Si105jGiFHkuX3fS4ypuUDestWr8uliqRVFzFqI1JOvaLCk/Pu6OCMTFxbjhi/9jngBGpT8lbb0L+twv37QDBFDipMnelg7Bz65cSAwbNxYX4/g/vN41xR/HryuwL7TcPhqzBDmg2yf4TGZzVTHq6TWC5gpT7+Ru1D2+EkLrldwcAw+LiXQSFNi6xZ3GeIxd/MUsrcNIX2U0I0aeL04OS7Ot3FHlfXEVtpO1yNCaxuPul/4hk/4OAxgNKBZ8NXcTQb3TFFJSL3VJ53pZ7Ky/ECC1qA2pGpy/KxEvv1ATq2mfeMsEZIiJQ3eAk0ZthMBenr4my29Sd+Ex4OD3L2dauQiiz+aI0ChMEhQdJXkgAbKQ9f/E4QxtUzaFjknZa9uxPDGsSPqD9S3Rn70Oy2l+vYpyEWQtV7x/AW7PQaqW/ei1lgED15BgHw5tXd+gVqM1jwev55ElrX32xlTqaeDRKahSf9Sph9OiuSql/GQ4W+8THES4Ta7L/CvLfOhWM3vkRUAZLvqIUFWkgZxZiqVTAsush9bAuJ8Tz2KnljS0yTX3heZrqCV/tkxcU1/LwpvKWyx8+cXzCYBDihC0Pb8xJe3QF
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

