apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgBTByIzGBDPnEcx+wMgFeDoW22L8JB/J5pa/ziaBxSkPRqPvDtuDwU7GHWWS37zhhCIjufJwylZHe3+HuSPmo2wJeiOrBb35vyHmds4behLcjslV8N1bGa/z0dPWnwnze8R7ccH9+N6R5c0fvbLGQRAeX/hs24ZJaDWkZWlUJqTKDYHYc439dvlk94dbwX0Hz4kVibl+Fl7blsI6MiRedEIuWDmilXg2Sotf1vg9xv6lS11NTFrLjQLiO/yaqP4OQP29jhmEIyVQS43Q/1NbnAdOWpZ7A932B2pQHuOVQM6PnUWRsuOQMmVEYEf+Jt+/qBuyEYc3/wFewCf+W+xvb2G4BVAWE2e/qQ5ER7UQRtmbOeo7CN7RSgKtZ7MTWCsnaLCidCAydENlX9scM30Epgar2AmbZKQRp2YKrUpbr4RGaU0+f7Z1Ig/te9OUPsTuMTLGtgTUzpTmR1m3kbsOixA/l+yvaZUwikeHkIIf5FUgP5A+46gzikwqaVTr82uqjS1cxvYYVAWTzySavbjGeb2uzApcKzfxXY3amBD6EJQtXMjbKpnQeV7SI0+lY2KuE1DA4dp7tMrZPZOd47q30xZvU0HVJ+8Gk1uMxt2irgD5Gqh7dJcCo0+eZUyF6uQGoZ9lqSmZxf33dosPaejoSqJqRVuut38D14MvkOTHziGs4jJgpSmWYSt0xlhVwMwNAewe7Ti0RpHUpXlvFNq7ANf/pZl
    CF_API_TOKEN: AgBB6rcphTiCLegV+Jpz0eCBxbNmstG/OoAClQoLi/fncLR6+oVVT7Y8s7Bkz/h0dCO8DOtHODyHAqbNRDjM2R0hsltm+y7f0fa9uII42Pk6d/8QHAqgk2FtX+MugESV9uA6/vo12u82dMwRBzf3WIX8luwGA0BfcwiwDks71mNW7RNI/3HOkPl/3GeRnGLzPlxr53YkQg+aFJ2nvtMJ3rgcECI4v+jWvNGikiV0S+ONVTteix4z3juFUKaQHGjEafur2ZIjvtq0lSFn1Vpkqc2rTeY/H9GYJ6MotQFKdDqibvCLn72UltKT6opoB6rGqFcysWC+JLaYap6w3DWt/TfxpsGILL1Epgh5PRJ2M+IMOF63awwOeHeTAoAqBumqvc3aNPLj3yTFgHMBSp85ZQG/EEp8TT0ZuC1WgVIVPm6Cj1v5tpO/hZFyiF4DfBlP0Z0Q8KXpurzrN9BqLEA/kxk56PLCZrYbvuN2inuV3EtU4FPVjH7wnV9ejaMO2UnUPsvd83JSClZIBD171rIf7AOZG0ZKneGJwjvSGEDno1ANIl2ilzzT5Szf6te4evYVefJplnKD0JNh4C+Gjq+3JxAr5qRflc1veAd2HyOAuRdW/6F1o8+AXcKi3MBDqc9SYp8MHCpvu+1tNK1tO8naEO8hI9EaZIEUWjg6OHjbnfz6zrE3r9jUwVfE+4JpG8saowZK/DkbBlL5mXdU+hhfWP+AWJQEE2007/2XHCoQNozEKmvmvjXwR6M0
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

