apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgDM5hHVfuM7WgXTe7Ii2PzlLfCsDlzilZPkyXjfm6kzW03NH1rmDXkZD9V5Qy4XLW+WNknhiq1dt/da7bej9yYz+/A7AWR0zpTDbqU7pjD8vRnrl10rgtGgH0vAy4z/pNtDLb3Ejuv12jbvZz8GqjJXE2uckvaibhgHeRMnRkqZJXQrQnldaU2UqPGul24BW6hP7ETLuy5ROLCEgKg4RUfLZESbmZDheBntXOYretkcoIyMwMRW0G3IQShSYJ6ZK3QpPz2kaDYyIwCYjdTiS3xx2soMmdDSpXdbf5rUNz7ZQY4N2YtRoYHwEuMgxElomNkMdNxfgzS6DLT6UP15xUtsItF/8fTeSPtUxPWvDWS5llHJEa+ksYEAQifybjqVpK98TS9TF6LdgNb5KgtvkzesH9hdmPBuTVcA9lIFTuFzoXA2RIfbCDgDDjsPbEeCBwR+j/YYKeVinzaTYT9gikT0jfZCvbxPspMyXCRNK4DDzxqxoaBXPA0ZTB3ygCQK9ZY42HYxdq8nxQ6sCi3HuFAhXAloGEV7FjL6sMEs3NuSZfOReR8PL+XCeiNa+AmmKQ4Isw2DV9xw97vN3qFoDgr5XnY8v2KINi4xAKKZTdlz9oy/L2228nnyNBw5IIxqFMtNRxLBOCBwRZbfQqt7ArnYLBJBNO4bP47Jo2rwO21RlbedZ9KldYZdfNHiYtVma4goEM2HvAlry9pNyD3RfjoaOia4
    CF_API_TOKEN: AgAws9wli80hMY88pvhh9Shz5ue4EGxkA0MmxREp7TxuFQxUOoq+H29Q/FggaW6fkK5MobBUN84HcB016fsIWNO/TNp9Rqri56sRTlFH7lFTQl9KVaghFaXcadCe5WRjNaH3qzF7ucE2RVBISsssV/QbunbRv4wQoFD8LCDJd2H9aa5Tk/meSeBCWxSaWnQGqSE2VGhTO6ji3HngO9cgMffAeeqbnDydHYjrOTu4QDN7dzhTuBb/O/mk6PtjLwb75qNY/iqngORwioh4kzBKQEOOzu8A1G0SL6lzUsPGVaPVFqKC0ZzDYf0vPLQ+kkUZT3MrXVSRf590GAQ/dTcRLrwzzZeswWEqUoo0HOfHyvVieskNNU7KiRxPhMl3lJ3e07juRIxfZuVSDRX2JVYk4RGoHgmPWi1VxSWYAK+YRxTt9RJ7M/py+M8EWibykfVdXR36ruzlUXRNJ+qWGWjmSfMwnVivQLI0hGUGvCl92Q+rkIyM6h3JQo3u/cqJ8Uo/TGMVqC4gyJUNAkw6qety1bwfaucfgpHBMPWla8dskDB1aGWMi2DYJWnF4SWKHAYhNPw6R6XzMkIDUYvUocXGc/Jq+nRLqVRA5bK30u1ctMSy3TPEtzagGAQ6w+0g8gZp6tbGpcRgE8HYftXB4bhb7o8v8VGL9oi4FNgTfCEyWGmp+e3J8MHXPigBbRFifsV3D9buA2UJAKaQgQ0qkJpC51DwFf4t5L0X8IKlZj+i26cMNGwX7udcNFix
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

