apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgBlZHcVdYhM5OEGceXdChVcWe4csRjxjI0F2caHLG68IB+4TPjsIS3zdKE2gfzMwURSg7rThvcqDiEorJkcFen6EWY5XNFcyBPfsbkQSPXfhGKbs5dzSLVICW9vMbc2RNyswMipxyEfipKpDOoHyx52wra9kqpMyT6TeoK5eeI9HhSuuk6VVN/mPS3q+QLneYdeDnNUKLsSmkU1XhYIzEQzVyEYx3KSnRfUfCgMlzL09YKTemX1Si4pfPcVzcC3oSpGEGdKNhdz4Xtv67gOdNp4mLlODPJhXoZncoX3FYPt0D6sUG86XAD37ynTIu6E0DTXUpPBGNnZjIWsOOSp3DgFdK+Ob8MV2hWhjj5GlkmcpYHB5+b5vjD9R83OIxIlC2dSrNC29fHn9Rs1FcGKCMdq186JJ4fagcTBjxojig41n914pUfldza5SK2iPiUy/U9med9YPI34x/EzyyPiiKFSpgkypFf6LcJJKdIDQvpN06iM/F22NnobzL9qXP9IjrhWTLVwFVKzbkYvqGyLSfi6yEYzP8X7qskcdGRraufD4LgZttHV3ybLTibE3k3TmlGnB0r0pEh7vMVYOB46qwgfhF8g3VIFgBAm+B0BtWTeqG9gc1qrPz8z/sbi/Cv74DzZ7Nc0P13sdZfMs+imgU+kqRgcMCHzno1eJAezKUkRp87OBW0TqemdDFJ5WxYuh7DyBWTM9Ekd7FZyEI38mVysxQeX
    CF_API_KEY: AgAcMbpw5zrMW/5MqshyMtU6WYlYuK7Mn+sMKRJ3MMQ62ztsOk+UkuDsIKuuty94kXWOmk1UnEH5DKKUpNzCtdBhUft9DZ4CmcAPKRqsrv6emSVBRoUG/aYC87/Yqzwa6LcLMCkl9/7V54wvAI0DTT4lL3R8l7Z3ytQmi1XpT3UFNqG79NxmWP9uJxiEtJUo68FIW8THdsPCvwQgQoyVS140TzxRhhH3R2YpaXjtXNCPv7ni2X7GpqoS8OuJXVQAj0G1N7reWuCAdNUTnq3OiijqqNVYQ4FHcHcLBd29vKUOj8tyoLc9SzolHUclG3SxRohWjq6nBtGd67zB7+kG34OMmFPbpUIXFPt9MJvyngI3gvxoCTlENXBD0ib7Veo8zUZGGHXlotxXz0djcGnMGxPZKa0eeoX7lesyEDsvVQ9FWc7GZECqUyW+JGjlCMPPyhYpxbEXs6dFb/HEu/PafjMp64KtVeVkPtQa4t2MLyRXk8Hpck5mfOlwhiLIJZys+sLdoUXvoe8kA9gzsszt20aH6SV3IQ7XPjt0637IK3mS8Pkvp1DKXuapP+fz1R/MZq1GyUM8WBUE07u/gXo5FoOt3C21KXGXKdcTPyQxNTWSUscRgJLj2q7wKv0AnUEgIPVLN2sE88Ox3ywuPqlPJCnvcasRVATUUUU2/FG8mq1pV7U7RrLwrEEcF831BcFnzcKI15bTOvVDam6E/KCzJ/dQSVBwTDoV03TDqkJAMYaiQBth5IBwNOOW
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

