apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgAOxZ9Y2xhxJ47Qh/ZTPT4sR4bv1/kLckgjrmhhOp5Nil6T3ZnOqhZZ9xsXd8qyABufkjt/OT1wz8TC9qO2nXP5lx/NWfugoAjG74xljjQz8Xml2CUIlw9jiDOvNFhDlH4csSlfWZYCEmEQaA7TGSZZOB19Hn6YtIHQOXVQOVV/2krJsUbldOMZlRijWNqL+s5rQZkSRJs9uxjju4CzF7nFHqZYoKE++WRRKAh+vUO3rpzNsD8PWSZ4lIAer+3rZTflcKDgg7ykMzOv/6YJbkzSm7vN2IOhMVtfKNJb3mAI00muMc4hNfpd7Xgg00L0gzSvhtAxO7/Jg5MEDYN/G5M0p0yUFXIZ9eqUKJt3lUdpE+sWxcJCbnxqys2MmkLCU0Akve6GJ9anQBYnneQ61jPGY8iBmAv2Yo7JMVPqBFE34ylBG/uDxvni+MTsy/RWlX/10xOAqr+VRFZzYngdB1ET6PFe99TCt/EpmyN1T8lgaoL/h7ZxLP4MUxWbVvb9Mewt3bQEab2yn7HmxPeXAVpvAkY1Et8vY1B0DZWWLl0b4hVhvW4obgBydSbnGyOG8JxOSSeIXLNGK2JBXplPk/tsblFV2MCjJWdtyGgjttrhzVYzhgOaX476BOCSwCnuBF8Qin+/UbZGTHxRHTURFheZtjMKcCgZ3yLcYBSHUQIJGYcM/U5IDPuBYfK72rX21aWMg2TtL9DvGCpxuH8YHfTcR9ZO
    CF_API_KEY: AgAeciE0noiD3NMIpQK+4INGceqZJ9nzYdsXhAmOXucFJk946Lz5OLBQVrYTC/GTwoGtG9GX11fpS3BgNepFW/Y91xM8KBWp6QIqjW0vORlS/lwe2LwzumM6EhXpmrW77yGHt5caRUZeoEGHcA/SBOiRySFlPtkAH/2cAxysWtundScaHKY9PyuRM5YJsWRs0Dncr92LSuoy3DsB80StNSrquHmdJyjFJxH0kVbPvMMLnYg0c1uFSMEzqlHTN5j131ijvXhZXARksa+QEGUHJMyA+9nLRtSRyBpMKdDAnpy4OXDtZPQVvFVjytqo0HqaxkK1N9UuEAqSbEBDfueojLMbQADXtfsumu6TieBIEtCIWXLK+Hf5FtYn7QCJ0kGYkHCbZHUB5Nx5b5g+lYcgZgSvGDZ1n5dFnqj10rjf1o4E77TMKWEtWjB7CVN2pnc/SNfHz+mm/6BXIoIN6pgwRmckES9cvB0LgOBTNWP29I0guqv+XYgzN3eNd8uBdkcnPWS1myfAv8q0+cuBijKQVp5H1uSjHmbjxApqSwbVZ2OF6TjOitzHYisoj2jr7eVyks2REmUWveG7Yfj0YmgFwac+wrgCU++rQ/RuWtTsva21WrFMD1PCPWWRC0B00nEJHURzzg7QRvyhFovWA52DDVzs/5XJb7ja48KWE/MY7dG4RbN9kzw6OGsf1zVas7sR4FzQjQ6OEUimN4IvE/n4qwAsnBmbvsEWoMOEa66moEB8zUi5WWlnxL+a
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

