apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgCsPKfZ3+gXEBH/PvT9AXlSCBOXigjlX2znHE/6dQyQqTXmg+AGxg9WEd9G+5M8rR2mUZJlOkB1l4lvgCxyIcn2wZmwpE0b5yuZoi7aGltFBR+DMjkl2FKlz/OW2D7PSKxj8lAPMx0pVOKQOCDKZ7B9L6vLmdccy9E8AKTDh8pvhUX7rBWerIU/Q8MT4r3TKvEaBGQATSAp+Enersh+f1OHbR85eL58Ac+XNR3vtzsDEzyU8q0KbUU5biUC6IaDhwiMOe0hLgFQZWpg34GDrVQd6OrL+op84GbC/MgI6KHhUPaCFTsgUe4lP4BLk141QILGXwG+bV2uGTuQ3Fnz0QrCqhZXl/+iI3XCKQ6D+TnuQV3ZHQajMBVtavUCSx91wg5qg5eR7nBwrvOux4sm5T3B1a491fzdDOkHNhO3Ih9JXKtDpPM5WEzeFfRluJRKwItQzdJSzGEIQrcWyuJyaJSEP38RJa5SSoGf8SDw68H6kaJk+/qWvuNx6gw4BGFDXhthcwnxR2OLZvRrTuVgGI4V28sm/nt66Ns2GbzbdP+VvUAm39V2KYfK4imYPb9klgLb2Lewb1kFFaAZ/ba6d2vaFTTR2H31X24CMzJwIAUhMDCUAaYCeGFbMOkgzMosqCbbc2EmcPZctnf6UyF8+7x3L+vCskjQmwaPhP3z59nUHFdh3vhSUw8k60tNpb8tq8H3fN2wYkLUck5htEAPpyB4K19D
    CF_API_TOKEN: AgBPF9OGuLxgaMxYW4itWJw8UWHTNRSjd9Tm2k0offFnxFH6cByXlszDo49kxAJlvzeRB324Td+QwYveFURkY7s555jrULaA7S/bgh+++e+ujVNWsvXsQnjLOjzLnuvcExSOansXWDUIFTTYPQ2LhON+JERoyeLW1kNyIQZS35rdHZf9TXcBWqrWYHoYklYcC7OwfK9+7j8Ux7OlOTh+eOip1uldOnGbL61jr2B8+14Qlc2BTy4OZyWxVWD0z+j2GVzY79mg/e1ku0+kLJYchUtKIbPLPVUeWAeo0ssV8mrOq6mZrdT1kAw08fb9b0ZW0yTkpdBAz1bATbzR2yqOZoa6L6FNd7bPyT0Q0FGPWiN4+/+v2ywjZby0Jz/2TwyeHTTnDHIRMk7AUXkLk3X+6tRn37joSFhQPZ4npHzy6nSZFG+ilfXoJqKj4lISie3m+tfZ03y/XRhRyfBnKpOlRUuGkFmGpEAP/H1jNQ8s1nwUg/15gNggYYm+jguV3JLt5C1iMacEgLbvcQk5kOqgvxio5LeABBB5jTd1vM8vH7yo0lwnw9jr1WBN/hTdlapOECl7v0vlaKf/KVUEZpjC2yQ9Z2OAbkfho16RhhnPj+Wpa1TpD1xUZJK83aP/5dCTZNiAxzU3rx2+PLiQvs9IkdW2ZFncskvhBdpksmWD/aK1ZcyJrow1GKNZSpNlKX4EKSioRcNe91AoIYYQ4BdLP57NTptIrVP4Iu0DRxcAChkePQtC2rGZP7oT
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

