apiVersion: v1
kind: Secret
metadata:
  name: access-token
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Leo310/lhs.gitops
  password: GITHUB_PASSWORD
  username: GITHUB_USERNAME
