apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  credentials.json: CF_TUNNEL_CREDS
  cert.pem: CF_TUNNEL_ORIGIN_CERT
