apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-creds
  namespace: cloudflared
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  credentials.json: CF_TUNNEL_CREDS
