apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgCDCAIrKhYLvVUWEuRB6JSmnShI/6O6T79hVrwSHOCGDOb5dl7i4mf3NliVGjpeBbvI6HOM1lFVVWSzmzeoBTticEk5cYKccQRZXa6N0gQhLxPAyrhFkV/qegAfaC2PQ7MT2WANY4prrQoZMsatUrzWJMiaL44yNXSWZGnw5O0drCDn37A7692qOt0jIayaUvOp3xQznHttIPBdNDtClMxEnYC84Nqn8yP3qRpGm90gIrSJNTc4opN3kjajzGNVhytIagBcUzqW06//KnLT5iO8L58x93B86qHP7/3trMHqSjQZmm2t3OWT6IDo/p5YyJBSvglpkwE44Ev68lkAUZtX6cdL+nUmmzyEcTHhGOWUgIPJwmfXrBsJB3IqlF5PMzqAKkKb/n6VDcCHdadPXOXZG+V7uDWwq9nE6TMMSaQP+WCe2zbQVbVPQSDgqwEhuHzid/tn/t+yu+Ey7raDjJ84TRWdVBgkn9Czy/D5JmJxuCPA6SY8rjCbCKNKTlQ+srVxFQ35wjlA0liIlCx0NOsWnKI4kQl7/hh/K/lUvZOWbYdBjw6B133pQ5yyFZbI3LRlLUT8Zod9DlIKMw2dH0SdJ1AspekpxKCl8EfPp4LHsyNgH0CrTiwFhwki5lSnHteH8N1bqIIMNDyQOUFpn3HWBu5eNKbv0lgDdjXvojSecr9LTqzHg44B8rgpJuSMI4qmPA0eZHS+9WGeJ2TGeWlseB4U
    CF_API_TOKEN: AgCnYbAXanqJJFjiDY2RPwnMB+EtEu91qGbai2VkQiR9fNqY+DroukwK50ULfnjqXRsJd99nvxmHjLY7b11xAluC/fjsQVF1i0Qj/1fHhSZQ6pGICN/R89nFhpdchrq7wHvVePFdHUZ7zWq7Ko1zfQYLrE9HHIIgGjdVNqpNHGbko9WpM5eLkl2kZTPZarnxfyqPHJn/uVw9BKdVdUYTRZIhzdR/r1q3kmnuBBDi23END+G7IPlDQ+lnGvJjrwB4+B4IfEozZkTYnBISKUX3hl9wOMx2qlEyxzqHLFbmQP4qPDWavrkOOGSkzEIiaJyuxPwGZNt2jsca0+mv0FTC99nMsjEDftUEgAylkvVR/llZ8XLECb+cWSHVXrAk/KCJAGNCTxThcC+sR7NWXM3Jjq8u6g0QqArRgX8e5diArsapZA4IxIhhMFB8O8eVEdSnjz8lLTeaYK+6i3U+DllgkP2QoFN09L/iS1RQN9jx7HS+V2mqDNaiyVI1zmd9joFYq9UtK02aqP9PNFfcFcuoHRwucKZEhdyEQIBAV+8G6bSWS4KyTY5FkB8zNwAHyjjxBdRLqic5tWrlD74PFA/rEwlUCZ4iEEdwr6yI2wScOiPrPMJdI9zXn1jeJ5Ihzmw7MXayp5U/HnPi6Roqp32V/qUFaYyf9Y6srgVNWDPT5Bd+ouILEAz080AIB34zP+VxEtL1qe6N6mVblpj7iCpvN9VL6dtyhBh6u/zhbK0GOy8SDs7IUrp6LrLR
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

