apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgBsR3WYHKLVN0mSFZwthl0z0j4TfXHLJv9VqObm4gXat64QH71rlQzO8WJIO5eAhUeOcPEUpKTlKpVb1283UawbKuHYd5LiQ2Wvx16XOJ70eQBFz452rPW+51XaXqE7Mb2D6LgzWrPkqGzieRIeFSUKoXv/33K83pwskRmAAurtP3NSIvEg0zk2+1RjAGOG4TtCIpHAB3GZ1ONws1AIhNecle5xrQeeLpCX8V1ivw+Paj+vGJVujMuRa5Lr5r1+11lmFlflBjS3kWsgX5miNShsdCyvwY98BENYTqCwTHSA+PEgQVUaJYtqNP+7dwuduzIrxBqVFoOmZfA8pq3OFCo0l1xqUdxCDA0cy6iNmy9HTWwYmWsufI0+FrmkaR1be/xkTo/WQf6LY/grhBsW8URu9lkiw79O9ILyjtRmWFvsjqkZNOh+FMiR7k8ngq2QkCzC84vNvngCGfBN8Cp5FQmDYgvJ6CJmHX7QA/ztrB0z+dtvpGdUuNktlRm6S4G4M8Eu/e8q/RwhWxtIfYaXfYkfQGdep6PH07i5wytYM/Q+Xd4W9FxmFVBQeHh4LTbrqqL8oQwWdxHNQ9NVkwSLE1RJ3KE0CSeVWeZjbz7RsGN9+wWkwjQTt8zMKhFFtDNF40lUK+FWxKrXd1BtvydwzN93hF3eUpziNv+cGt1fgsHpC1oV3Q0fK7Us/ItpePpZh4KFuLOi+ZEm3ItGUd6Rgr2LsCWg
    CF_API_TOKEN: AgCpViTxCMlSVqj2lpTPI0+1+on/lOsQbXkyDEBkx817n1Ab31q/gsnwwc4uCdFqQD8257VCdp7Mw55CL//dzJiyHg1Dk2jMOneya6+jDbBgrs2opiUSnpK6dTzhiKChzYt+WYLgbeUDfJ2jeAMOhxV6B8FszcnAnc5kAOjIJKU3/v0lkrKI1TpyjZnE0xlUYarzg13BjNb9ePdxdXwXJujj2CyHRx6hkT/8uqpUw+VFfqUIVb+p0/G4kXuv4pQmqRPP0YO7aYdL0pjCmiSTz+5Ld25u35GRPmJ5HIxNN3ktzPYcdcB1Q6JnTU7SVDT3geT9SDnEHnoJJ7gTq13TIbHEm70fmu/DamxENhczCqyB2tNKZvh+u/AxyxyFhmGjvXgSQKBgQF8rvU7UFWBvfqMmpttdAWhb3rqfoz3W+kpcrI6S75om3eQ2AmZq/MKG9aTxxIn9BLDDFXNV8KIQRQLemMsJg3Dd8NS28ufQ5LSvh9vdUTMwrS3M5lWh+l7wbdXismGn4hxUKIErND/h5OAd7WpPbA5B9LSrPot/7V0jvkVMdGq4oOBRUjVHkWzR+O6aeoy0J+nBey5F4WV1FPypNFwFDTjw8HPfj69UzFvwl5YkBtVh2IrdmCD4BmRJkb1QEelVGeS4V/AMUc7WNjXZHZe9BLKupN+rj2YXShK4Lgouxd+w0TLWA+VfywIPm0X1qWIuNI58/Fajd/pzbDP6NxCZ5Ep6BW+UEMVnjqECy+kSz/FvIOGX
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

