apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgBBe/JIgx4Tbhw6hPLNn1eaJtjmgvdUZPusse/lU84wmcEyPjzzmIcZIMrTSN8MPLyThVhIohXcLiAn0WZ3930AI26PH4lQ2w/dUiwBzjH2MkmgmD56jE/I7DMEDa26m6t/qMFm2kJ4J2zwipd0x3FmlEYDlnoS8RIo4rbhzhkFasholxDU/SGHP8e/1j3shxIKF4VMku2bSnJrNMOpaLCzv4y5lXDsau+gJaEOh9y8YiQqduDuQpT9oIMuWDCoFm2JnZIynX1ng3YWe9TSZG2eSpb/U5h8sUqtghhNczDvPZgm/aXliChw1gdSJVVBnLbf2xcISAFYzMcUCyD0gF0d5FegSBCCMF1Ml0TvSSUhoLoZ/IJWdwE4LX1LwCddvamycnnsnLUfjsxiiG/k0PaYrXk8tM8Q4Jxgro4FFbaAm5v72U8jesRrI/tisA6DnxaTsWHgojwQolrs8WXnboxZ/jionN27fdqR0w2ibulvsvaU3Vo6HAjaWIUXmlxub49CvrVZgfwak0nhE9R+l6KtFGY2/tTuH/h2yiPzXitMEIxDTa7zPDHG6p94tym2iTS7kG6pvMm0mcU0PESLqgHgEOebPiPrxYjg8JGRSlM8owvI8JVPZLd8bHpnHJneS8yy+H8K9hBXdIKPh51G97sU9QRaRPCNtp7pZuJ16G0RElEbwTdMy7RF9pxel9Ww22T+691kCTG5eFUyXSDluzWk6PlO
    CF_API_TOKEN: AgAnwNzWx0sihu0/j6w4mHD1c8CLSCsEy5n29oklbRC2e695A/+lqApnpFK2zSrvTaOKecO783wubt9o7gI2zOtkrGPkRZbrN5qmgdxVPxzTX2flqq2viYM8P8Ygvdy3gPrs4lrSYSa/2S++AE+ZWbXdXobJRuPYWJknivFBAy5UGHFVqLhTbKpK9pIjg5qvAsUeaLmpyjDUZYW3ROqGkZGQ7gv4OGNLWhjvvgfWIhIjkz9t6dV7uz3v9auxnY6xr9uOW6gS2RgqcOte2x5QWo5wjUkhk0xo3RPcD3JFLxCxQXcSDg4sgrQpCE7eMavhm8lEjVaGsog1wHQoNIzPT7JDSiYLuK9zBIU0NAEsAkcedauwVNC2+qSFpNI1ATD8IcJ7AurY0szskHwMaGANA3InBZ3dzre+5wy9bYuolL6CL6iqjb0NDqpmlFwfvVRNsGhGr8wmfIay1HmO04OVVwXEi5IYv5XOGejGmDjvfQlCwiQ9tvkPOT01vv/k8GIAletvkpXDY3zP/2KhmYtobSlREQ3uOcD1xMeaa1lIKSPC+b+Wv8/HfeEcmrz39OjB0sYQ4uIhKSG7uljTubrX6nCFvRLW4Xs29NUvA/WJ4NrXlsTVzkfEePWeKG521TujnpKVujvWjUsDvq+GXCMzZ0XTfruYXnvzgpVL9eUfS3c9iH1Y06L7ob44JnWSNRyFfDym8QdYd8yhRuJgKwGw8JbofePJc7wFFbBOfdZ7tZgccg4gH8jQYii6
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

