apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgBEgkg5/QxhjtwKMd2/b1NmpJgpcRwpWS3Q/XRvw8+dlR8gYYzy1q29g8sdtxbmQuOSOT1Z+CiW4K3pQnrjT8lPxcFkDS1pyZHX8uA5T29t3sriCGcdo17/aPfJLYjouNEWz+wGxz2mG1jf32Pjqo4mk/3wBuwnbwSsnBwSbgBBa/SgzRi6lti3+NsJeC+KqpNYishNa9L59jzNwzdL/I7WpzHAKcWTis1GOBLa6hqsr0AnUKoODYTwMKO6U7kJyJ0SHAADWNZFrn9PCNL0kyUqdZgdjLSYSaawc6dVE6M94dy0XqME59qugED5G4ny4EmeQ99x17c1JSiki/W6vQeb5krRpW2Wi1RG81WDQBuZ1YqSRC+ICZtUDhbfBuG7xkiIau6rTCIuyWNc8oSfxUdyN2U/TE6NlNiXTh90g3xFJ45HeeCJITqS/F2Id7TfgJHPUF95nalurjLLf/c+gaJa+zCr1RmgQkQyx9NNxEyGYlxLE0mgvUS4ZrxxWGGuiRBWDckDuPyZ5OT5i/4FJzu3yAZJudT3SJYoYfyYDT9RSzB7tmvWLXOUauJaoEmR11Lr9BJ0vKI7DX35CIUKKzUU0JOdzTV4Cy2P272LQfyaC7rfFRtkZHrNtivbIk6vo9l1KcZT8KWA2XvAa5EqUED+ibS4AR9Wuk47xWoDZMkqO88Lu9qbPUyEvvHhKP0JNmSzRmmkWqCij7VTts4X3hlhw9j1
    CF_API_TOKEN: AgBeAfZvETiNzZmZD/CD9cM7UFUvk4tSFu53Ze0DbnDL0Qef3fh48SgP03clrn9N2ciK3L0fJkZyVUmBvUKIbTX0v+aMLj9s46Wb23n7/H2KWxz/G9KUVLp9cYfN82BQZcbJZSRpl7M9Jc38HLkGTe+u7bSv5j0t+c3uvCw8hgtNogIphAyzx5s8ELID05MV57YhmOfvR3FjTzg0Mel/5SC6V603DEcOKHAHqOzH//xu6U1ad1qdqZO7NKRXLwi6X+1sHExNMQlOBz1664A0x1QnVUiAvJCIDW2SMcAB9XdUXNsXGTDh8vU2itAvkcFhgpjSTrXUOYxRC7DrGChLpW/UfUCjjWhmaOm7nl6klDv1jzra/SYPEYcNndbVGdG6XI1zIEyJlxCLOC2ARBXNud07OB7wi0wxh7OqabQhgfXE/B0bbM0x7EPcGqb5qlFWvK3F+1zOw8dHFqVCBOzawIZ60/93dVugF8e3DB6fUIwNWfWRxX99QuOrKPgvGm2NvPKepjvNSDr6gc1yJAlz/Ras1UKFogSnmBUfrsxPtQxlBM3ux+qNSMCQCZHyj9toh1uwVUrgEOU73fjySLnmf0uOTfzgS1KN6ktLYbqP+faNcVOqRrbkGl2CPIloy5BpvkUHTpU47run+o/nZqYgvM/S0Mik0twPX0eqAt42/W/2zPZGUe2hfR7lZidVUBqvitV4YL//qjFRz7L9KCmX/9Ti01c2dzZt7u5fu/DjTcb9bPuAuZ9xnChj
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

