apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgB2jlrQ0o32JRIdrOkhpRZRAoetm9zbKYrwQ/b3lEeJYajIrR8wX3Oc8KiaFQhuIukCivkcy0yh5Nniu0JBtoZI8AIA/SHs+UVYqmK/IGivQ+HvjNTG4KMnUdJa6gefR8RE3zUr4PqxfhEt46gkkbMfkIgrc+952Aba/q9pldRY3REIA4JHwxSw/qp3KAbAA7tFpsGOKLJbPZtCWFNEM5B1Ag/msDmRRNtIB56PyeOsmBsdFcf+AdcdYGpYybR3UGfr2yiZ0rT7MT2Yz52h61KIm3VrwzHjgB4z3i+hrElWB6e4cyCrP0rcqoJWwm/Hkgr7jtPhVpmc+nUd1vbIk3P75B5XvVTUFdyktdu6zULh3IORv9QK1W/HZuhVl261DrNwGWiRYV8He8ObhOuCPEhd45A+yhRm6SK1P2vXkmfE4BnXMaof2XH2jt5AbEiTcBbYIMXrtbXeD8VJPskvgJNLUkuIht5hcgyvjhAVH9cLTAbFvi9pfjurBm/h37LfcIAeXXAZeR0wa8bO4ulJmJeaEsydc9ucZiN2cFa4QuwYbftByFR/oLWqK5aFl7iMdi5nn3ZQp/d21NukFhVOiGWzxZENj7b0X4pmYRaaAz2aSg5Eg7EmKAgCIY8yWX3ueRKmk4CSYgcUKyfEUw+j4ra8yVfplpMooUPSi/qKscDWOaNf/qjzVDuqJi3J6X8xYe4+x222GR3J7NBr6eRwVsEkDzsR
    CF_API_TOKEN: AgCLVfwK19jSgQ1v9o+FD652YjoZQS8a5nGqSo5+RkyIjNTCYBVN9J6GdrAO1lo3yMdmVFDUlcg/GGd8jOHtXeRU6vCFEYu/htgJaSNLjN2Jq7SvRphgvjRFgz9tDn7Qu/RamNfpi7shLqQaZAucnIAVnbteYXUT8ebX9BQXp3p9jH32GmKTqoThTVKjArP13QvHNzIGXDgedpcqIG1LWowEwFYnvlqnbk0ekPks1CYjYTG8P6g3yRIKfCSY+b3KGXJ57JxMvSjERL7mNJ5A/Ot5SfSqx/yTheumctl9Zkll0TjLyhqqr40Ck5RShSAIEUY+B4lUwUVYv1vTBx6Dg6Ge7LPPjd6UdCJWweo6w7JsQOEg6O0Yh0Hp0wyGF2TPwWre3Kk5+OEcaCuW1hSwOudCYrsMN7eFdA+mBGhWy9UlfR/1iTG4xTOJm+3Q+52N1v7PYH3iQ8OzT/EQePeKwYdvj75epGsJfXznFn+6N1Y2lyE+lavwwDUa8jtIGm0mQLWtQrIjcDi6HfuwdTDWP+2DqlCaN0koHBAAD9B1iC5DIzg27skgaXsKh/lusgdgWKaWVHK2WKZIjgB79qbvwK9mR9X8uySkknzbIcYVvG4gXS3Ou1exlrxR2LlDIYCQyVsAz97RfcPaaVIgPypskLz1IcRMqlbL4VWOzIMKX7kk301XxAvW6G5Uz9A9yYonQQPvICmRxnF61DduazwjppqafWBxAIxmuuTddMl0D3dE+f7CnCnunIvC
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

