apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgC3/Y9MALNgGjYjywlacyU5i7lJq8B/mlBIaazQCatuzFxoQ4LUbksFvSYykzrigwaRUNb6jgdaH3syFWr5lJzvepn5Dw4en2wVoTl+NhJRRHwEaTBeg0U0UTFLJ5ur7vXyxw7i8xxGPEWQxqP5hln02ZUod4P+xdiv5HjEliszD3JdHAat6F3Z1V4cLT7tmfQhGXuv2rlnw5tK0T2z7hYiHK6nWhNHVB3A3Qu5nZbBZS/X4tl7bxip5e8d0SfE8jTf8SOF+D9Rue9AXH1xMSwYuvcl3bjvUiWAWpg5qNJKzg4oxu0RtIVtROXJEwg9P+3XNuCNDvzWuJ4+GO8iC3xguemRM/wbcE363IXrQq3mmaJLslIr52dfXWKf8+TC8OVW/yIhqR+cjdy2qU1RO2YJNoVCm3NAH0R8PFhXAPJ+d+gG8Q9I8kouGkLfjxH56VcEdVBy8oUVj0CBZtmGLDrvXUDeGyHNVfv09j3D/itp+V/8YhhEVMbaAWpJZmA0qdKq04MTlx+nb3TiInKXqVgig70vtVBHstP7KGHorAphyiFn+ycXRHMvaLyLIh1PqZ6bNrHRsnOkDYDUS0mekAZDzI8ursQN01JYPlc4vc0tnKeY9M3/vhCX1ohB9CebH0oqZec3bHC0dlnyx7bavOQ1LqJKhw0HOZiwBg+EJu3KoGrpruTFaT3j3oTpCmBHV4rMZtU4XQoOaxoFHcYGQIXmlLiF
    CF_API_TOKEN: AgB4CDzhi3Ua3JGYmLziE+D80JP7M0siobLBduga/UO8k2SmIaKhRi15NapfQfXAPG8bp8OI/3wAsgCPMGsNpv3o3mVvgUMwGWjSHmA6+ik7YND/jHOChFuPq2OqtF0Cz2Dg3+5b3Lq/GrXYGZ+0luBd671X/VFvIDUVV8ul4yU7tx5ReJJEaMdr8SZcCbifVYMe84sstiQUu1do0x2kwJR6G3jIpusNgxV4KttqVhAhtYbqVo78pSiS1hYQIGD5VB56d2FSFlwjks+/mktC751V+OTutCzI5Hcgopd2UmKCkxN+Ohd1wJUZhLUa1V5BxABurInJjVcBz/x/uHCeKxHGJTu+S8UOK7/QzwRmaHEfg9NYtARw6DGnitmInZnB0d1w5gZTKTIYLoXoSujjknpl54JWY90QQwT+wMfhR7KaX7D1c09/VSvfVwEGpcQqgGQ7a9Zva77j4byjFGZfUtGu94Y5LtIwQO7y13RW8Q7AX6t4YLEzyOiu7BeNOwb9Uz6aWYbRpczhw3+qZGBoYaCM2CMeH7bm+FY9KsdX4JrPj4V2A2fDdeJ994E3OjSUhFy5/Ly88EbWc09PXmweyCoQN+Fox18CznKjj1j1a9x5uAEEgMQ7uVt3O8aRS76Mb72rIPevB2NRk7jycly+3kz1+K9eKwRoIqefqbGTOWiG7QC5lJzQySos5jyvov7N/78GZs8sihQOKJN0qcSU2KvZwiWiMLt18HgxhrphgLdpn2F7AnP3RdLn
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

