apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgAraLEBL4y8Jczyf+y6ijKZaaxNfaexfZayo3egZuFrKRHNAsVtsX5kc5la/vv8iR889IAuoT/dr0+YgSQR6KlP2RBxGTBnRV/Y0rwrQ1JwYMI4CYU3OHuCDoMwFWow7/3ij/r2JsZG4qiV0lrWjqQeLr6EqRn3KclSUH9g7gmlE+lfvquHZbFAgomdzL5uLgW8pt+ygA7pLTUHh7rMPuMm4a/W5wlmeIINGjmPXzHhFQ02kEu3dIb32oYUaLug6nyOEPQMWBkrfOsBdT66hpx/nEv68nsPTAHhBwR6+FgpFb3An2JHv2Sl5LKtJsGF97JVGilqItdLA0wPUxlK1xrZxoA3Y7ztYwmifE0JFMuy++m6qtU7+gu0xvoE5mK7OyJ+HrNMmOjs0WvHetUFoJcnnQ8CEI6RSIbtoPZ1v9JsoVeyG6i8IFVslqbkMtBEE6ksEZUO8yyNcMZ+mZtn8G5co7/UJVy+WuA+e46BaPIvw6Sqf7VMieZF49knb+kbg07mCKTEtYDQ74Tn8TjBNxm/R65OT6Bc/hL+N3IQOP6nk2DP9laRS5HKR7Ie5GeKxT+mpMUUEQP+HspJZqKMrZQufpjjBSzKqjJTQlhpCD67rlyAWHwkcRLv9VqAkGMtTej/8dXOioXoOYyozTaG4KgkpsJdOG0ZSDwWuZhl5iEJR//gkaRPM5RNKt9mDZo/Koc7LsRgOFWZ5fq35C7XSMorJNQE
    CF_API_TOKEN: AgBgjRoVXBH0yNeJRIgS8nKVStjn9B0W8LBu7fFVnjyMZ5sDEE9hYY549f5XqN2VT8qi+1LJ2ImHdjZgQgXAED5G3eIa6XYum1lKk2xlbq4xnWjbYUvxFYsWRtMYgOd4/QBWi+KTttIVgJo42M299BFc3NfWeBFz5YL0f1s3hPW7Sr4jO4ln3h0UamVAIv6ok35t1paoY8kCQx7ErJ4q9O6niyUEGP/jvD/0q6wRP4WEt9MqfnmyG0TKWZ/CeMap1apY2eaXsTFBMvv03Ebh6L+IAJKlv1zKpLbS5Dq6bzx5ndEAVq+QAFludTttDzoyjWhPMoVosUgrBdhjBFo7VQ+U2tsw//hDIxJQH3o/aDP41MLFvo6cjewFZF/R7HJ2uqc5n0cdDkrStPW1kJAz6j5CRo/f1H+7xCTdbduULNfBcAxFqWwlTGYtnhCmXgtskYCZjm1CxtMkM4/Vd7rmyjIVzA63G0CuVUYMRuqtvkqMrXfYTiv/gGhcBSxO7AgO3G6Mb9YtokTTlpVcHAocyMsuqjeDyrr9tzUnn2mrhCW1eTxtNZ+K+o1g50lQqMrBaQI/snyIUx0ChdEEO0o4lT28nJow41fJWdZaRmZp8Lbn1l5NyV/KfSaNE36T1YMfnYjc4gCpzLOeqwvpkYNlMRPiyzK7NKU/iob1O7hfWIC+s3ipUTIz/qhfwdxPQCBOrlSKZJ4a0Sp0KSyOuTiKL+ejK3wjNd+kj/BjHnGt62B1iNAnRe6lKJRa
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

