apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgDA47/pfGxTfGVkSf83e7sZZWcUubzfM5dnxXgkN6J3KqZ9/bJcxUS+TuksUtWVbi2ZP08OjIjfzpL57A9yyoZijunDiwn+G8xTB5q30fPlF1zERSxxBDL0zD6I+IpMgaYjoR+5es1buVVin06JTql8axpd9wljXv3Y5s/PMFI6TzgVqyh6CKAySAirXd/DTqZnKYTzeBTE1z0kvyXeShgb9twEghuB5kCBrPPUCN/4V5wlDRcMVem40VNuIKyhJjkth7dlr0+SaIc2pzPG0GSknB+EPf0zbgNnBGUEzjwf7XwzbqkG9hxWM2RqzUmSUglmaH9c4M2UCsk6fo7g+KbsTia3gaaHY2Hu9VGKqmdcQEC7GdAjro3dpcJg2s/SmC9rKhfackAyGmq+zP5ExaP7E+E3ndtLc6XiLk8mAjwnPcxl2SMSYOsDRfHt51F1h1Ra20AwZQFxbGO/9JT8oLKOMA1s/m40GzuvV+L5SnqLXxRAB5nX5PbObQmq8yzdvQ+cBiim3iByQJPsfdrwk9g9qQPKtgvCXZHEj/KS9oNDS8cqHPBQ+uYysIL+GwgmpVcPcq/VbOOXvtvOhCPCs+rvJbyxXR8F+3dZQpM4rPXUZSdKoYPs/HQIPVZCzW9dDzdZO9BTKX5Cs+0ggGI5Bo874VOKiK7iZWb2WDHGuAXN44Vye7Hm8+z42ivuHHm2uD75L2nnO37+rESm1qcwtVbPt1a3
    CF_API_TOKEN: AgCMLOZR2b+1TAfuMg5KkC1jjsvqvAYfjkxhFcOgJKLudS+/uiISWNWbIxjwslsnkszEVknUS8/XOIOc7f95A+ZN49Uwzqyp5dTcu3qJDn1NPHmzR36ftisxGMK2UYx0ERW1TBLh0Hw22S/Ovr1yZ3QLS4qqnLsgAVWom6GByWmnbHWcT3hlPZ3nfaHMfEuFINhAUgPrzzIGq8zzipZrk1ctQWlGfuA9JfrL+AZtn298bZ6r38zrK3K6aIZ/Fi1UWVLbojhnO07ks5ryocPPZnw8B0euAg1bkVH1URbGzpa138Z/iIZjzsscmhJRCnuVlNQGiyMKpDPii8oNKFDLM3UtBGzqowNqn7o6sqBEr3m1ua3BT8ep8PiUoPdK2FFbcThhj+a8XShg8O/ygKndxKpEXerEQbgbCA5VTqRO1KcQlSFBnPnk4zrsINAkxphtIv3lWygsj/06pRFLaGTSB1a98szOReHysxBifcaVvV6kndu+ZpjQ+MoqfsswSZQFlQuQB19i76CtThmFVFRv2tjQZzZ/y/3V9WvMX8wb1mUd5bh4bYukOu5o8FUHRs0ksHwQYwMy6hthShyQbhwPdT+3vfeWwqqioSauHCAzMuIajtUbetmxKS2OuTA59xbin+dQklRwDQfK1PVpDeUYZ1QrBRllSzcbV92MlBdDfc0tiu69vpT1wxG9uCm1OpuO6A4vRcJCO1qPqZbnzGSv6maO9oWXqWlOUoourLjT/RkYr5e2sQWaMZGB
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

