apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgAaXMR9IVwpox4uoLzjeg3reOEqd7pAdbUndRJMCRJUvjVsCsNgN8f54hWEs8/aeSnH3X/gaRhyjnFtDb6A3RPWE3T6moLjtzOArhqMC2SQVlkX3FcO1VXcX2CgD1FAkgT3Vb6irDV7AEMFGqzQAsaeke3mSP/lMg52C2sR2lncuEQxFhJDVo+Lg7c0u0BLXICWM7yJmjAt+26U1ge/NomRgQVeyB3Z8v/+A7MzzcIqmlSyAzzKj5xBngZZEwhYxciA3/MBxfP2+hOo7F6pGpbh2nMjUuRTg0PAjF5s30ySjzo8cCJyzgelcYBcFa0t9vIq8r0J4kUwy+DaCp4SxWJVU5G9TRcaykKue2ryagLwsQOe7YHh6TEx8y1HTuBD5kFvub1WcKsS0+P91y4JteQlsg4E/nesy4PkYe2oTHoaQ22AEabBJOUOA8N0sfEf+I8qQ2mdcbL/uWMx6+0Mnj58SARPONNMf6Go1W5bjQ70qO12YeQohUyaRa0lkdFCMbGtREhqO/QdLTHVqfJiu7xFH59QoQ4bNl9wJdXq9L7TqI1tucAEYqh2VVyD89JKTQESs6kQze/74JuzddhXUnBlhCaP0SiCIcd/OMAXdhv1CUtmVmTyXIKNFRAAJwP24768bBKSwTYdnpvplKv3kIuGndGD3i5/OSFTaX4vSAr/Zljl6BZWlk3hsOUh/Uf/Yz4VIccdaOT8MKPKwdPRHVGL2yUK
    CF_API_TOKEN: AgCEWR152gbEGkMpQ+3d2zS3IzsFWyRu44xZPXPHNvuPXXeZdCFwYmMwc224Msjl+PDKUIINu86zXDxbupP3YCjG/Cn0Rr8JwqeiB7XX0VHUWL9Tf+1sUA9tPEv4K3PIdzcJQHV6w83Q/L8bRjILobIhyF7ik0B6hYCTv7aPmZtDmxRLpyoRN1SuQInM3Zfix85mrwCMPCAOH5APoX2b1Wn7pYn2w7/YHGR/pGsE0nPKGihWTve09sC/ITwv5Cfbs0cBTSkUsV0syQqGiwjViufJC+8z5nQ55RwGQDZC9vaxsPjEy4E7Qe0CeltGlTjsGdXJSvk7nz1PW6kRkqzmCrrLt4Eh/tNUgawQlE7ZnzM5yV7NRK7UAjNs5rpROts+SHkgGopTS50gGlGNlzdN7npn7h8859DyZKm6jtvGe/p09KLAK4/FESj7uEDq358lkGEu4nOnNX1qJobDK4RrICtZ/MAY/2BHW55EVFBVwubF46tPSkgR1RSY7gfmuiPJVx8fuBOmsM/88ZCHbGYxmWYzOjQB7Tx6Iqfl7VWn+fPUIzYpPyzzoJudLa40NYPgpjH6W1aYvCkgDnCylkB5m5siSQZWK+FEearkjtEbhilhxYsnjf5NFFUJD02JwCXOyf+T/Ol3XGmCsMj/aRZ8p/y4bFonq4Y5GLu5AlMumbwmQAVU6zsdCVFE6kJa1m7vE7SpXVRzVMmQ3RroZ+/Yg5tbBk0Q2bz1gslSS5vEnJmoRKm/y/Y2+83N
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

