apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgA+AXXjKAdLmuQUmCjObcYEL8By6qRGFU3849mlFzCvpdVSrxA3mQ3JXMYj+8RLo2FddPptBnHEJB/e51yKgnttzRsXAmrRMHo6bxeyTs45XcqzosBSCzwrzan4kYgfOlye6EbX3WKkV3sYPzw1bV0ajsXQ/frAIQY/KG2ysThZH4EFq/tF1D2/rl9UXTeYhtZThPPOqS21INTtHfWr6QaJWRSkC1kZvgKAduzxH3cyfMynKCUgX/lv9oVF7cHlPObwi6cMwyDaeDzu41XGUHfaeVYjuKPsc2qwdKhHaaX+0GWG6Dz1xr3gJTrJZDrv5AJBe+m9cs8Q2rRyPnIiFADn80hcyky5tccjE+FfOLLciL4oC5v3GzbBlJfNDGj2Ci+wxGt5YYnpJ6A7LTJT19oj/pV9bFd9NVVKgpgK6ZQDaLv/fCPbHS8V1iKDbLGujgRvugQDepyF4urd4QmhfNsR2Q8pGUIzAOSsTwPElHgz2/uakBTo943qFJzy/0yT6IrNnvW6u0R/tW3W8UetQtMwQF532CFsva/x1qhFEN/zVGr2PDP3kFpjb19pbo2pUgAVdiylYNdPru9UaeswAhv3QKmEHUD14a+6xSIZjM+XQZBrMcvHL0yG8FJR51VgWluFW0oTyhHl6VB3oFyonWje5RyKbyHusetIvcAhBK7BzkMxxb4e3H+/oxfjV1OjIg3eRuBN2+EejgYWzetN0oA24U7Y
    CF_API_TOKEN: AgAMtqak1+fdyWJfxQAqtsGZ9MFzFwFp46IB2Yafe2cSWf3FYRWY3hiZ5H1Cj/AVfj+aJ2wW2DsI2MFCDLtnnzmhSPOAVP102PJXelAL+4HRuWZjv+REBNgBiM35KsdWCXY35FbCFquzYav3bqwmmRxSiAfmDVH3ZuHd6BQHn+wnNyEujMifzl2mfnvMdxMndR2BDMh14pIPNXtXZjeeScGdQfnHFoZQ8vtxYA/C5o+splmHF2Z4a8hXcnj3t/dEFbWnfM5/N78LYMggwJWfF1btpbiAO0xXz5LwpbBXLuiiUr+Qt/TYBpSKkOl9ZIwKI9rgUIyZn8aBe4QvepFZP9DMb2lIdHp61H07rAyXFKJ9vRYZ9zvPagIekXt1L4Evk2PsYhbnF/LQSnzXfw/NCpTz3ijEVFokse5Mi477i9TG6/VH3j8PTDxnyHzYYlZ1nnPEmGfrc9rDXbMR0Gm2rYt/Zn40iieMqObAt/gxGgp3LRN1dAim5+U+jx1TF0z4DYJNPnvS9BkL/pFoj569AUdcbR7OlUT8LcKvBVpBBvr050nI50jhNX/6fndh96d6L7xWFbafXi3V2L9SHPpMiJuGSKCFajlcWMglEepSPrGfnlOkZmtmYTJzeMlxzPx9UfzB5fvsOICGofJWHNlpD7qmXgK/OTgtPj9W07aAQT/jLLK9kXk2zbHN0C5fRGlB3gBBtmyDoSHUrf+NM1Pc837F2K6BCdotuoMph4q7AQklHglGQ9MI87tz
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: external-dns

