apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.gitopsrepo }}
    targetRevision: HEAD
    path: applications/external-dns/source
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
