provider: cloudflare
interval: 1m

env:
- name: CF_API_EMAIL
  valueFrom:
    secretKeyRef:
      name: cloudflare-secret
      key: CF_API_EMAIL
- name: CF_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: cloudflare-secret
      key: CF_API_TOKEN
# extraVolumes: 
# # AWS volume(s)
# - name: aws-credentials
#   secret:
#     secretName: aws-route53-secret

# extraVolumeMounts:
# - name: aws-credentials
#   mountPath: /.aws
#   readOnly: true

# sets the lookup domain for external-dns
domainFilters: ["herginnies.world"]
