apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: herginnies-world
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - service: http://webapp-service.webapp.svc.cluster.local:80
    # - service: http://kong-proxy.kong.svc.cluster.local:80
