apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgCd5pkoyjCVrXRRR7L9qkOYqbGnLwKLjV6+X9SjdGHsCboHCEwy5E0X0iJNoyNEb2uabYELvL9VYM0QfL/5wXmH/+XrUYWcDCKhN9jMJ7li6mxj5ofM6sDMCYGDH0if7sWheeDAhRlHj1A0V8UbQznFyMK/526v2PuS1agXJcDs1J4xDxpUTJc/60WZGyM6GNpVuEt2lfIGww5IGyCLnWyw8KaVno2FjNttVEkEYMfcChZemUF8Y9RLQzBlE6i+bIlLs6yRfVa1bCKw7pApcNC3M/SydnphhPteQWDVjMwV5jFzpzIQFLdkNh0O+15GM7iMtsV1mco8jsWxLRaDPtigkf6XUPuSAg8IJRifv1NDLJdQXgAhWXZ84qwZkO7G5FqqTCx2cmtyNbIGNPs0DeqVb0p2ht+VFNHy4MJ4kFNfNaLS4WdIVU4X6N9bCw6Nqh/f+hTZmfOiNh2E8Ooo24Cw+acz0hLY8lao2exOWwz07NZEtduBC85it2qnI5/z2dM70FF07PQMwv483W+iwIF84KYLWx5726i0SaDnn8ld9Q9CopUdYZfdvXHyLpII/DodceJ8IFyZ4urYWTmkBvXUiDlHVCOKHh9Q4K/5+VKAOv2dxA0XaBFcKkkJRUrk29ULX274nZEUe8SlgvDVlhFdhHmjINhLazGtDJdyn00HIQMzaj7y+8UZP/+4LfvqVOWkO/RgxDtZdsRYuAwXiekMzedWKG4YNRsbHbyD4x6RslcZUUqTcYpi3pzIokMEwGFoWZ30SMiFzjTetY4zDTip9/ahpsey4tPiRi0SX7bZEdwnCtleW3XnlZtlXXmW3f37oHDhlVMNAlywhSgbyNcDHFbpD0Iz1PKJLoirrIe25VJUnUzyavfM/Bon7Z0LQ0WDPP2hBN9x2Dkc6fClctlreQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: tunnel-credentials
      namespace: cloudflared

