apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgCv4p7qA630/HS4m31DwvvWflmP+QW2meE9VBkALUfqJdSl+O/lIWiozu5bRtNfUSq+0RhCGNEJc6ApQI+QvGHQFFpL5rowMIFWIly1N8oQHuYmTZmoJMKSlNqyRZRZHzuZYVy12Yeacw79FuwPNf2CqrZDexqv1VC7g5ZxbQPwIAVQbhaBVzOJhtxxcECWIEWTGvaxjmC9AQ21y55jp1Wy7X83kJEf+aus8E27r11CIECVfQOGNLVdcqxUY8W2DbzvJLi2JLQtML9vr+hP0CD57HB22fmqBNGFpHBFPvzrvdmGKczaT/RhF5l0wKxgHbRid1B9F4C94euAYLBz805IYPJoYZhWK6vWvWomcBFtxurikoYF8X6pXO16Tb1QUYCtquiyNkKKDqLlsazlEEdMqr7wqXYbtYP55gqZk7lu9r/tS85ItRYvlGsYaknnh8IM25BaFRto1Kiv+EwgHcNkcKdtJJPBJ6GJDXxZ5e2VZuZztOJUIgW6KIMBG/d79FviqDBuPqgpyhNL7WtTulUbwM5k4UgT40N4OZRFYURHnZKiU3fBP6siDFYKik74YG8/sOQYtxVk7e3e55Sn2iGJqT5WXglR179/I01qWUkiTp9Ee51WAe5mEFOnhv0vOFQu4JJ8lXMyMNpSo6xOjkSSHqJ7+Fdva50ZwIVA4Q0F2GA3StuKK/6b2na1S0OH2jLrMJCSVnNfkfizzZqyyms=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: tunnel-credentials
      namespace: cloudflared

