apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgCDKPztwMPXk8pU0Bm+WCbmfBzs5BCvdY2l5KDJsMyZpy949v+2s8Mg9wPI0lNRSm1nOzfTyiXC+t/l5kMXQvAwCGJQ/HLNgrBuDMqM4ETWjmQbfs7wV3CSZK1DKyafgN5aD/WNd3FM2/5KzJpGChkyMLIfNqxcXChi+kHd7iIAC9JYuwer8VzmtsDOtbaxLVCFJUtou0MMmor5621/udKMf4LCd+Dfdt5zA5lhoN2LYuE1d3YuyvRYBjGyImEirZ2uIl7a7/yeHFIHGCdCi5dhzRe5kkIg27SrPPekxBEJppZXCp/ou4Perbrs3qBKlHHRcjIvkgmB9VlP+4AuLHmgm9YfwMu524Qk5Oza0jW3T0QkMDFyf32lB7ARtsWWSAQmTN6zRM1lu14Cqlw4CgKPF2qG14D23BD2ZRCp7m0qPbNazeD6m2DDQ07nZg8PivNw+CqjFt3i/sJ8qG1jOvhHUbFAJaAcZMag1I+YGhbMKkJl+pi5ObU63aq0ITe6FSrp4mRdF4g4cT/AQAZR/jREqy1TaXtJaWw6Sqzf6WdrTNeesE4FMWM0qpN8sT1o5u2cnem8xGcjzNoUDEg9qOlxu/DlfGXALOXvWV/8M/hdaVpaDXX7yu7FLi7SVD4Vdciw3JGO9T6Is8seP8rsnqf1nKdLl50eTulgzP5ZzPVtTRng/alMT/YgGP6HvRfHws5YNWMk0asJufoLvHL5+VyZCWwNQqGOEtsjrx6J+3Xdxln8RU5XwEwhrwPbIIdfbB0v+KjtZfyXYcti8Pv9+qM9dRUdHKnXHZ8HMZ3ZLyj2+V/o3LQJNkZBArQzYOGpkLJgAierHv6PowSkoc5m/BKyXv1PlIpURH1eyIYbdX0ed/H7hxSD9E3u6cO3vmvpn2U/W2287hDmMCoKoGFffSVprg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: tunnel-credentials
      namespace: cloudflared

