apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAiV0ylua4Nn5+4YGHvtT9tJx4ReFDfqZllBsBJbYZMKO5EFfraZ+B8rBn6GhfmTPvuv0l58TrffonYG5/+ab0Y3l/Nmspk2D2w+zUyzXtIBEz9wNxVUi/FKCbuzKg2e7OTtJIY58U8vfBuM8yOanZFPvZhXh7di41zkyuF/CbM000K34V3ojHVyuhwK6rZVYm+ShC6WaqxLhLljnD4W4oNRHwtbTaF2aFvmQR2JFrZWYD7ZnZRpfS7Wb0CWfk5Q5qre5oBbbxeUbzCJDsTXlJR2cJzWjdsLlmq421jDDqn7tJyiy+/f70YPfiEtk31RWqXdsTRO1JWO2LMO4hM0EsFx7qsK1WOC2y+Xc6lNA7IJIW8mIvFzBFy4c36boPHQz4Ztptez4PV9KRBunSYje1JCy9tAjShe/egrG58xFRxx1B/kC9qfejtLAvxZalLaI+fGiv0QwLtfosd6XrH4AOanD/jHN4EfiAFL/8Ip3Sg25s5IUaXSmGwPZkOBHxj6VlbX5YPbC9Lt+T4SA6rQP+5+U+KvwoH3v+L+UPv4MMRu9QKQYuZwLtV7wVTD8uzPpY60LU/z/ExZ+tMP6cG8vugBhWa9bmyw0M2BlbHlCEtZ3s2dno3UY97STzK/ixXUe0RB5cwrvm4RK7Sva4eZWygQkuKvdgLBM43LAvErKYk45EXCICLiAcZLgiBGawi6Oj1TvD35SA9eB3kPuQClQ8=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: tunnel-credentials
      namespace: cloudflared

