apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgCqPKz1r/IZ9FKWHCBjuTtV2xs8kTLjJxIa2p9AwRBXtazCj7ceNtqh60qtnVGRsRySI4v7CGLUo6WaZD7Sv5dQFuorYwvV16lyzcHmBN4X70ncXOQrOapAgIIyTnNRFDR3lO6U3zCrlIENltvS9vLSydP7/mHU0iCcPI/rsF4fDmQQUs7CO5nCK9BdHpV15B329OWEtNkSKhgmZiCq4dRqp/aR7H5/X4UebhupBmZekSi8JWmFLC3Zryh+a9ygHWQ1NE23oxlTmqHkme/ylqkUBeGWnDpS9wLblHF9klc3ow86xMxo9StKq7GVT1e1IFiQJ7RBAX22dHJLowA9FSgK+sQC7Geq6lBZH20hkPujaIgxuBV0jJRo02hFSjk4Azd1B7xwpLgckItgBO1d+Jp8wlxI6K96n6xdW9IAADKiCDmG9AgEPcBn746uLJGenNemU8ee8Bh5lzFD0qhQdJgRPCO2M1EyO3jYYCKpH1ZLo8t3tSd3o/KfsL5c5f8EI7+SR67wSRbB/w0/o51N0rZEraS9sdjhl3F5Aa/A2gMnW4XW/22XNiskAgtB1wq38VlC6AFvYHKie1IvQpIHWtdm2vFnZyRQRvDFKGmrQ0cYaH3iKMSIo+v9mm1F9FbIUd7wh1l9vtCzBcnRboF+kpj0exOqo96fi2NqkfsnKsiBECcgQxS0igdfC56sBtz+6LTC4zm0QZ2YByGCiWYJ99Q=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: tunnel-credentials
      namespace: cloudflared

