apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBSAndy2d5QtiCULiTGkDE3ruMO4qAMahyNCTud9bIfI1oD5c3/Ics9TETCBtQkF7Eg7qrouGKxjcllNScF83h4Iu4JTFezVbUcg++6HZxGc9pPSveZJJhYcl9n1GhfR2knSBL7Sn8OvhKMtVq9bnj5j0dUNUrjrmBtdkVU5EQ+iC2I6GAhIwnhWkjm5KekebyQwK6IqcopgwhedREKqMRiRMRma/6jsAj+UvdMUkXqXzv7vsifVq3yygzV7bUIUF+8gGgNKzjz4k9uv8Z83ezGj65w/EZ8cUk4CrQ/epqIpgbVv5WCCrvDepB6tPlZtbrrCIP4Rkd4VYKNIdWpKx7Wp20rP+ZqEWzECP3j4HIERTYeaKMnMwTrnpsrpBQ3i8xb2A0XnNtyDOhMN9dpe9PhQYqTCXxkoWa//yL/w1rJWX4Ln6mUD8WcSms208VUmx8EwPbf/ctxarqKVwcREdWdt8DQ6ekMCjvlW8ynLzzv0EQSnWAEk/AZOp+TYe+BSEpvMKsbW5MO7sPIrDKRIcYWStCa3uODHCES2y2F1kJ5gNhzmgLIPEXln0PNJJOKytxmXEzouVembLKlrjBUrpGF7aosfSCviyONcX0ghZEksL8f8MW2dAoAbZ1mrdqyOye9T5P7/QlvZiPSphyCcKr6iGTxQFCho6EalZalZ6fUrBrtWarHaT8FvuETdajCN3H8ZnPiHgkab804j3PGkAY7ucP8w9iVWjA5aDg2NbeKjYKmgnq0c41M7Vn6SM/cqDiUAf31OMqokq3rf3Bli6CCOrVPN1Sqp93MrRIMm2kEZavHMKf1qo6unwEunVIFVUQ+EH88q700kzwi7suOCw37jhjZM6trvng0zQ+qjaEKo8F7IvgFmf9sATqBZzv3+tZAO52VeLUWPQqKSvfBm6wkYw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: tunnel-credentials
      namespace: cloudflared

