apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBI4KPlf7aCCXDqtL5FzTq7Y2dJgaECEJxlK9tVvCqHZN5B3gUysUr2ZQDHr2oheyr7BBbQIP+OAdvQ3EMbmMNDqbWh8K/cED51m9xLR+WvMmlwYAre9vWJ6i2AxdRIuFFFM/0EiBqkiSa307ldXDc+2rbZyiuUECIZO5nOeWRQ6GW/q9jTX7i3MbWQFmEI61do4lyxcy4sZSZ4NNGPSMNXR70kjAhV1yBlZzn8bY1Rz2vZifwryfIn2suF/2rWY54cwFY10iR+Y5bZngMWYmYse+2NpDUQcipAv65gVjVrOqMubWIne3Ff9Cb2ShZFRM7apUtlnG6TK2TpDazyfAiu2l2Hcgx1a7JwWoB3jRiDfHbgTONiS4jxJzkuGh+n/LeIzCrZwotkG2X6BckRWOWhVxgpGxc/VM0CpEVTcffjq8OC/2clAKG5Z1CbHK77Ke3EUP73wUovVc06aVaIv35IFFs4y9drGZAD75mmWYmmXVmaUL0hXejm4cdtbtReYvQjWmLDwIMTaRc0UDh6MktxxdWTV3iT2SFbq5oF5s99cy1DtC77k/M+mABmmne+OskwlpxXssWK9ykwBAhK8rlKA4RvCpqDN9k67Drwn4dtofbRNK76p7Do15nEC/p6HjolecYH7Tiig8OTr+HCbov+rFICmhDreBGddygp96tZCtdqwrubpWF7qU1NeuW5KYWSFsgmmSox10LBEOZA0iL4uAa/iywtVRzfBjriemQ/b8yPlOX5P74w60/kfdBOhbfoAfiG/Qz3O4SyZMuv7AY81JfHn7OrRCMbyt1+MCrXbk0iz5dAlHftPQkC51/buv9TdfPX+afQ3sISrO15RhazWpM1hWwPpF8Xiv5qpDR/IKq2FOgecMo69pbXdV0x2MKa6pc1xmS+Xk1rANrzyl5c9Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: tunnel-credentials
      namespace: cloudflared

