apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgB5OoUivs9A7iQbbUUuynxjsVERnLazyhmnsY+XgDyK7kSCbkF9gjAvUAfRYnYF1fzTBFEtxUvsXkyYdvWXe+EU2pLg5/XZojE0ry4cas1uyPrZ6cUwK2mEWe2/qejEixgWTQ2XBy+UR/xUhCoNWKIY0NaRDzG3Cr0rgoyuTBtTRTozBp/qFLTEpZHrAuSvxJ5LWo2V5Rn+E0UjMZWL4fTih8aIOwK1vW+BT1PNKdi10MOL1ocuZfZMbZ4B5baeJnlSt+jKm8HsxbBvaGDNK4fCmnwUGmlrby0nI7UjGUcNKTk6f4Qic5VJ7F57c2DgWWz7rmgXYOL5u2Ueq86qdcHCJZuBl821H5MLRlXSAX6VZy6dSfYymjGHBjZAlX2L3yAZ20uW1NUe0z+rl+126EHSxj2lOmw+GYxtCkNpYAwDii7QtDP4GvEy3QkAHEyJ4wNbjrPiFTIBasCfkGi9UZhCBinoaKzi3Qv7oNWTI8kHCLCyggRyAzfH9YS0NSYHBVGM9wC+/Recp0MugRy4hhVbr2Hcs7EfV2v8Pz68zFCPgEvwypXrrjgkMeJpOHlbGw/BXKFHR1ek3+l8IXSqqECPi2eotjBy6IJQBbN6A/IDlF5cqWwDgpnzt29UJudVQhAfMeqaKuJkluKPTbcIBGykqKS/O1VWFw5UCDYr95UyNaa9ExiW7ivmajZolYAPFaAfHu5yfY+UXboHhaDrVW8Z9Q44wP0/Ky67aTI2zeCZJofyGxLhRV7wdhVfDYw/aQ3VbvvF+n1Ez+AKBGOcwh1RNMoM97bvjAHKJ6RoFfHkSJpdfPRKpCJRLjzbAgbYy72UL0y/lxuJNPQp5axHcf7jlITKQj41YWe9EtYDjaKhWc9oi2TZtdsCY8jFxFrC4knCCkFVt9fdSLOUIY+3+tgFjQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: tunnel-credentials
      namespace: cloudflared

