apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgCljgYJf6UjeLpCCOKM8TXhk/6PZCBEELUHxhfBSf8KCvTdGo+EWvU8q9Q/5EL+HRcjimA8OWy7v+gBV4wxOub0M7w2L+HxlelH7CfUwjfvFuaYInC2TpomxOYtByvqgEoxw5TzTcMCMu1o408+Zzfgd5vO8gUxXCr2ilgK9MBg78VmM3Dn3x7Wx/LQ5Fsi+iBE3FK2X0dlmVJk/TZosgzdD1KYTPaOX39y8zX5+Mb7FYcMGDNgZtfeDP3356c7YnxPfhcGF0Usb7YTxaH9CGLHLYkXbryhnZ3TmqrJnnqhSy/5uwPAzkpw3zicOBn1qSpRRZ/onLt14KUA1iRzm3dX7+8ctKfOj96DKEwPBNjwI7aUX6rbbQCGkkYD5/WinT/1B7ZMi3MiBy00dNuw8KIYomk4g0iwFuWNlLcgaza1qXGU7+ZVHuqaOyMM9hrZXIdATYC8hJLm0rAXKKxRJ9sdSlo82CAZJJgmoId0s3IFZ7lRo+W2M/cbIswmiZ2vIrMB+pl3RUDFUcpBqaOT1JdD5eiQjs1JVISCL5uP1km72iFUbH464px1etnQUrmVQuUYTIN53FtnQ/GAoutUi9tm5c1y/RM7kU+FruLn8XxWCajEFryPrSYZeV5A1zcR4MCnhDlAB1LeHw0uNPoDdo1UkF59jsZ4UhsAjTIuFIYL117HfAPzokErZmAB9C9kgO89XirFOu5Nhejmkgka9SmqBzRVTr3TtpfoRGXf7sciV+yWuvs6qk+XFgmWWu0SH73X7Md7QFbyNm+ZZ1pnjZCV7hVcrO9GfK6eKx00lNI3E0lXWDLihS2Gk224U3gjp52CelmpovkNHsCNvaAKWPch2eznaOmBk1h7CzqHeDyshAlTFJAZMTc81CxJL1TvUEXoUs3oR93o1AwoKyyx34OI+w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: tunnel-credentials
      namespace: cloudflared

