apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBitiXSJuNtGig0A/D4plTFNSx3Sa9q1fmPvWPvpibCkuZri+wEq/SqLx16Whk42ihul6MbN47K8Zbje7sKCpofuLyuOtX0PwrBgwqKFQNT6DKthirjKmj2JnB3TViAkXmlc7USJUoVwme6ZMQGqNsvZSw1QWZWhXe0MAwXA0ZDResDLp9lnsXL5AWfsR3Kj3Co5P2NtPbZCyGkBhZgUA12khk7LGN6LKXlt2wG+uecK3jjwYFEO2wRTyBuko0dYP/SizcNATFJuiOPbtoe27dD/oj8/UzPEJU9p2T6/oauOg1cryHZOsUto8CAF1le2U1qWsjJmqH1pBBV8qUp2ByXHj0rsgNHw1jg5bP6ln70tOJLCLxf4XGk771usLkh4CHgi95exRjndjD4lKcxFQR2waz+woZi2ikDb9iFco4COK7SCsIAh+mu0dRA+6ci2Gx55ogCaKIKdHDN9Cd1EmlOw4LUyMNa1bBnD6wgxM5kKxUmRgaToxwdKRao+coBLCldcaEiZmauXkjW80UyU5fqci7v1vO8LmQIEgIuLrtggMJ3d15HQvwd/zspfjSKxcIyiDbz7mC7fHN/jY+YYfQr3krY9Y35EQiajq2dLmR8Dw9iJ6wfDQJiH5fTELkw+HLz+Jk0cDcK91M6uuZc0T8Wr+ih6kqGFk/trqgkCQPaBnOlL9wuYyBe+YHjJwwyR5AE8vdP6gT+7gU0nan/8b0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: tunnel-credentials
      namespace: cloudflared

