apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgDAqBSUQEJgSPrzIQZhQUS8ixXzub90Wwm+bWP2puYICb7HZDOhT9qmAFCEPCOw97zfJWueNCwcY/9zSLMn0rLB/Uh3U7d7vGTV2F3IEbhaGmZia00X50AfjeB0l6MBeR9RczNAHzOmqnhtXOFx4Ke0yAQhMffWSn0/0NksuJy6h8ZNjP6lzcIzEwVUvG0lvh4oC7Q8N8ozoWUkkPWP4pQ16pOQ42lSE/LfW44ZMb3G5xwj+ed566/WS2u69nSZ2c+ev2QjMVuYoUOFGIx2SkOf6nbEmWWEp0MQmmXz3/RPHi3IeZgVvdF3gkyYVjHNrA2Jlsrf9rNGAhgDNMxkPiARgrMmea+NlQoJ5rHou/CnW1OfvxiVYx9KYw46P1gvJGEjeooEudXkCwZ8jcvpXF2AaPQU1sJYzGJmMzWupx4NkKYAvQA9IRwdUN/I304cB62Zu6zbaK6cZ4xcspDEawGWXT6d4QilWZ8upWIj1Ue1zxrCXwYOd1lEnLZKDGlHfZmAXfn6+zO/9debQ4jS3wRagT5npkScQq68V1fqAmPrJs2HBcZm5KjdpvMfcs0OrPC1NzukIeRoZQO0J1GwpsZNBw7bKT4J6L5NiEXzfWKEgaq3o4a5eNmi7pASBNGG1uFxwXbXVrCz/n1YOP3U1/juAWeCDGCq6V81r6KFLGBvgSP2sCWFyBGrK0f4ZRNRYCcota4SsFCj5sv+l/hK7iSk4XyPK6Dm8/4DFnX/i+VPqOVaU6B7U+nrrmLh6GzL7Pe+ly91J+F0TSgqRrOMstR1mNwooTMuxdoy5lKbxdbfexVFW5heUdSgQQyPj2YwjvHxGTTibj/mheCeV0zbXAmkSurQSQpGYgKOWgZVpcFvFM0zHyL98qnZjzZO796hQhepnNy+gs1MeRIxcIR++cFXhw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: tunnel-credentials
      namespace: cloudflared

