apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAY1Kl7Zzhn4qJ5ri5Rv88HAFZ7OxvL1uWgYCqSMzsEb6ExrGFDWqHUqZUsKfQxV2TgqUc3tem9N6eYvy7CXFYCAD75hL6QtYRdJ/NUTDyNUapSsXPVYNqf6nSHDiVaXZ1QW82mtmIvopHh6ofSP8gAlGq2Pf5Qtr76OiFi6QkjjQo1EShqSXpC+jYIqUjQhtU54d3TjhO5kw2yIFJ8hetvp7dL7sJ5Owgp1TPP8ykODAbXJagWMclw5OG57tJJIbuRxzH24VJBx4Id6kFtvwX42Arm8uHtLE+IJ9IJRYeIoPTgwpyFXfIRh+ejI99YKcidlL5mAhv0ElQZsaN+ee277au5TwO9N1lfZiQyUdNA/cwDH2IituNnY+gLja4qNXP/bVzLQgyhPy6bi8A11Gwq6aauSeX7SXlixlkvn5QLljSeiNk5+AYxMTLT9n90rWGYzGGFi0U5qySBqTZfQk5pf8wkpYpS3auxp7IQQNi+Nk450qHVdsxUDbjVWJOfn1B2UajiuzgE9nqlxA/0nAS+3sSsw8d8/1Km++T0zgUCPv+AQqob6tg0sMdK6GaHXcbfepDpo3j5fLZFhJtuLt4dIY3OXthdPAmDq5tKfealj6bQzP8+AfyLlMaiTRGo/xIOBeVQr09eSSgaOp5Cn70DeTwL9waPZg418l4MmTQZcBhhJZJjY90Mnh0xbCOXEZcetdl3aQEWMkkREKxiqjE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: tunnel-credentials
      namespace: cloudflared

