apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: origin-ca-issuer

resources:
- 0-namespace
- cert-manager.k8s.cloudflare.com_originissuers
- deployment
- role-approver
- role-binding
- role
- serviceaccount
