{{- if .Values.deploy.cloudflared }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Leo310/HerGinnie-gitops
    targetRevision: HEAD
    path: applications/cloudflared
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
{{- end }}
