{{- if .Values.deploy.externalDns }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Leo310/lhs.gitops
    targetRevision: HEAD
    path: applications/external-dns/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
{{- end }}
