{{- if .Values.deploy.kongIngress }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.gitopsrepo }}
    targetRevision: HEAD
    path: applications/kong-ingress/overlay
  destination:
    server: https://kubernetes.default.svc
    namespace: kong

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
{{- end }}
