{{- if .Values.deploy.longhorn }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.gitopsrepo }}
    targetRevision: HEAD
    path: applications/longhorn/overlay
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
{{- end }}
