{{- if or .Values.deploy.webapp.website .Values.deploy.webapp.matomo .Values.deploy.webapp.wordcloudapi}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Leo310/lhs.gitops
    targetRevision: HEAD
    path: applications/webapp/applications
    helm:
      valueFiles:
        - ../../../application-list/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
{{- end }}
