{{- if .Values.deploy.webapp.website }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Leo310/HerGinnie-gitops
    targetRevision: HEAD
    path: applications/webapp/website
  destination:
    server: https://kubernetes.default.svc
    namespace: website

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
{{- end }}
