apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: inlets-access-key
  namespace: default
spec:
  encryptedData:
    inlets-access-key: AgBt3yFigQfAhthOxyp2FmMARwtiHFRPNOjksBpdUgLyghB/OqJrMi54ZIKhksJemS5XaW+KZqwDKdrFKsBOhQTrrE60G6Tb5AdQUVq3FU8IdkP1jW4t6+X1QT1Hpj+qs8mBW5KXSsg4AFVi+cicF3RzRCY5ZaqhE0jyzo1VzlgNSt72gc3ylWPlC3ekLQD4za/ePR49dXKao/iUWuhBzgxWXycmbC6HUURSkwDsMeTUGhbbLvcQY6v4DE0YHDbvqKyGLQiWF9cBYftvlVnFTcwadrIf+H0KEF4wVrQzVT2VASTXW6JGB6WhRHIIA8R5SlHQkoliqQtvWK5Z9jkvp2/PpVbYFWHe/fVwZW0VnBvGF+M7q31ke1lhaKhwN/v0SV5C8hwDaF5NcVb85c3ShMRQmke+11HSKypVd98xIv2TuM0xI/n6BX5sfCgAUvT9Y2gwmhkq7ZwsVv9gVVclm+0i6dGNM/vYsk0IbQ5APEDwp4efCgLwIn1tV5WT8sPLc2S1/Z432uFOw8/YsihaSX6XJ+oJBkFnP09cYeVHYbw3XbtBFnwOyLNwQtiA95El8Wj0yLT580VzlEV3zArEBaRZqBsAuZrnXN2mPJqLSU6z3zIk6p8gIq32KMyGZCsfkZDi7S+Mp53y9hoiLpOvmmP4VxVd49EleJ3oQvZsX/Xcw6jm4eq6pKP1tnq48M9HxkorvRh4/WsChzw1/3NKXO3krMtPmW/ZlyNQ50msqRC/wsI08ThNzw6NcEEvE+GSP41MMfVqxC8ie3+g/HMvDmNgY9/b7RSL8w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: inlets-access-key
      namespace: default

