apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: inlets-access-key
  namespace: inlets
spec:
  encryptedData:
    inlets-access-key: AgAUFuCwFqe67cJHapULWW1wCXekqM4Z/ey/FMZwjA7gvwakA/otEKYbALOcFfybf2bzjItY69i3oc5FgYTYXxWsgrr7z4RG9OcEotJHdW24OERthrz63vUkT7ieEk5b674KxuSpcaf6ulGe/ZYFvVJHwe0XYadrx4JObtxvaHS5aroLvi8Q8Vx+D4ZaHvmr95oTsP3yHuir89oygydQyWcmZQF5CWInvuqfnmXMgorPm7jOtkbhXHmcOzKflU0ij68iq6rga5Y9+qU1QY/Twye8+7mY6QaohX/g5X9tBNyp29yidVMOOfHhhJIWXs6sUG7l7X7EZnWd6ks9jliBI5IoAuirI8y8DF6bXMQLP872oHQmnemxmixb0L/EnlGjo+eY6B0RsxV1g23WPiW1x5ScnbrOY3pGCz+ImwteT5bLGVEX2BVXEEYYcbm45FrrwhECq0MxHgmBPk9qnSpuSAiBkTxXEsatCmFo+kQ6dv+Nru+TbHKmE0Pjwf1W6dXXHC0VzXI9yoQ883ssvHigbr6i5uUMUZVjcsnOn6LPqeVWu9NBH83UhaTR38b4W2knBCvtNWotnTxHm+TGgJMuffx1nNhmKJxIIFIYQ5f+MuPkjauCOo5ByWuwtI5QCYeny+reXzmh5PdTu5NaA9xVnVIDt6Lc6Ct5PWtq2gyuv2tHCoDrW8vuiOWc3tsHuoKFktBFsZf9DdlTbCTUfL95+no3V8elANX8AK+OEdEHmvkzQ+HGSpWqtPf+jjKzyhpNpUXYRIshXxRc2BXq0Rv1GDeH9guuVIya6w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: inlets-access-key
      namespace: inlets

