apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-ca-secret
  namespace: cloudflared
spec:
  encryptedData:
    key: AgCplh7SUyGbzHW3GxP+yvwZ6RxuP+LOv1ChHzK202VxfsEfLOrnUAyeDjPSnk+eVxNrvl5iPl5yKZtLtHQtn0tDAA1cY65dSiKmmyVP8W46kEI6ekDrNm0l4GriVXNUbbJ6Wo4YrLjJQP6jYKqlnrbrYS4PBGvYCpEIFNBMdyT7XJSdV6MDuD5ieXqaAhqge2yZBwcjVJ4Xa1kO2kStY/4GLjb0xst9sDoQBdjUUuJA2HvqmMLuVdtFkYp5Okhm2NOp5mG6y4NnoIXEkcD7TuGrWCS9SSP+CFep4jNhAFEdovpwPJVc2M1jlico6LIHEfLoWZUcaJuRVaJCWK5PEO8H28HouDX9rUwLaGoKRjfdeFxDhmoOB0mKc2xnhFY6V/adlh423n/2RFifkCNKy2tb+0Vl6M2yvnzWbjytApX5LsWhtPr3y5GpuC6zy1aCKv6XP4QQgT9+biBglIdYWPMbsfHCWbMU+PiA08aLL2/WcxQQJlItVWrBwBDY5+SNUeL2M2cA5sBdSs9ffvcfQ0wN3tuyRjpY4oz3K2qDqsGbss0+2kSF0+JiZssDWFxWjYT17YjBDvUsRcRj8zltGQy5gQR34TOZFmcbxyump/FsShZ8lY2LL4xTAwSUPUMGSZslue4vVBurTUysGLEz6qfNkDca7r7vhD92CvsBLNbwxUD75HHvVPa+T9gYv9v9kXCZywcu9DwPBl5jtjXs
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-ca-secret
      namespace: cloudflared

