apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared

resources:
- configmap.yaml
- deployment.yaml
- namespace.yaml
- origin-issuer.yaml
- tunnel-credentials.yaml
- cloudflare-ca-secret.yaml
