apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgDNZ6++96xeV7MWTka4KNI38v7eyOn7aRExR1gaUo0J/twrGevQ5Btb4l99Sbfj4a0sdLr6amchQAsAEJP/1RtrmaQ8ennWPXH//9BKF3q+TP9E+X0UpvNlyiGnPa1wdPcPiQPckpqQAkZXgGElpFqqHaZdZmh1wovrEEzHLohHwkQFurb4vWur7vWDmEsBbM0WvdAHUhOHyJk75ayYcmHKOOuQxS2HaBXLZJvf4g0k9rzxRaVB+oqrJgM4WI4lJK6g8kGqBkfIWmG0Yrr+aR3kfTzf6wCLldqAthm/cvkVlvbjxlVfQbt0vu8c6POfGMRpNueJQEY6Dmn1EMMkLMANiXgBlFkndrTlzNkGPUIoAOoAw+Cw6OJZ2pWQvEUDNHb75fwKKNbrPcNwE0az8dHPTWUC9Fkh2LDGJAxph7n2kk/lg9AGu0f2RHk0XTrOw7ANhado8l38+6VPnUv3s61O6lk5chHlLoSXgYnqJLBIPkDmuoDZ2jzUBPo6RhQOzaNZle2+4tuh+z7IAFivUiJyRNLJUH06X3dJVFVZUmxic51/zlZY+HkHSfbEPHg10V6tx7gnXQ5UWOhywIwmkP3rMbGlbEwiNF0NX52lzVr7HAmxgCxXCldryA9qjisLc1cung0PmJwoibh8NpdRmS9FziDowMpVlLwNIZHrV6mKPoShMapsdFod55nCIpU9hRxPnyr4XHfcPfS7EO8yGIw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: tunnel-credentials
      namespace: cloudflared

