apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAmHQpFdcWjeqzkmZlb5dEjV25y6k/JNZKrNn9ONuW2yIA6WnIqcD2C7C6zyeD6Lgzzo+VLzwyiF87B80Zy8/u0c4HFYpEcAiKEV9zBQPqI9ckUgMELn1i1zUl+lqZihjdz5NSKfwSInoasPPTSvLWaSOu8YBomhFxMk8t7/ylv9vhMGO12gfSFbxgeFVe6FbnqtePtufmi/d/t/c9I/9hhKLtwswKq7f6yv+rx1pOYiyJ0oB+EZSG3DrkTKjmL0/u5x3ldyI1WhcChJbg2arNPnsBZRk5IwNE82qBzYWNjFzOZuOr4fH2Q1kTzSkPvJGnTW40yOv+jftYoaZMAlY6tL8y5SfrzKtCpDPTpiI/56jM20T+taWfR/ZEgzx5E/0UQOukTTj0UWyaU5KDVRyp6w4wZQyHHhk7qQtBSTDbD7zp+fQDqq15kYz7vD+S/pOmAyvt3xcRKPHEvHYv7sF5CgsUt3jkrKNDLQXvVrDEOlzUB68GfwIHXqIE0EBC3VgcWHvmd5/ElaEHJYKhfyqRN3SYQu3+rcNEW5rqfxBGN9UsQxZv4bkMPLHbmfNaa/olMPHmynl76D2hiUIud/jEmqKte0Lp3hsIWwgbO1/88rVlKvvx3TwOzhv5ssTCLGqPhiBtFOlHIOi0E8h3NS4BoIPZS1GJJQq/UXv6yMWDmiWR19LbRPgadghMbKMP7V9UoWgyM5nPAX2OVbZPmVbY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: tunnel-credentials
      namespace: cloudflared

