apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAjqn7jKOTPFxBBORo7kH2PbH/5Ee3cyMuEA/ETd+fVl2VE8cbWwkOYTA4h0VYlhstOyny9H5OpDzygKQOqkbge6AtqEs9HzmMcJ9Gt0CAgfurNbGF4SJIlD9iVtE19aEoNFhYDWm6cTPN22A62W9+7o5lJEqpn/ihRTl8uRY2Oa7zlBnRy7SpWy7cq/5p/okbJS7OrIvMyoPBEdLdVnw6izdotTfpEgDVw3O3HsDaUcFrgha0uJs0tdDjbN2Q7raSBAqRN+0W3o5dR8jibEsAjMz2ZCfs7OZIyy6IZ14oz/WtkyTg6g3AaGlfCa9JmCZcdH8NLTMPe8d3HjR62rBfLkETIXxFejd876F0cP2kIXuiaIDXp4eLku3wJzOQuDQwFg1saS1/N8Yv28nn9ar7fQBsm48v0CBdWe4DfzgGHkdTxiwPHn7dhr13hHF743G1pRUZ39UY+ZBfljV69UnYf+S/QkfT/qtGdEkCyKNrGwozmGwbiOLvwFSKz4RycHn3Zm9GWKwkuF++d+Pr1RwC8TtTyDwuZzX1ZOiseEmGbW4yWo2bknIKuVhjHKYyu3v5gE1+mfbs4XHSHMQy/43unOEVB/Y+3aNCx1NvhDP4y3dC//IKZSmPE7p6yz6IlMl2EKLi2Q7KTpOxz7V2VAPp4hHhfJx6TM1aNYIDLKS3GPK3/WUrTr/XM/2cIdQ4y6MC1M3BNcbke+e65OyPScsg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: tunnel-credentials
      namespace: cloudflared

