apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgB3WOeXDkaeNKq0ToAKTLBrs9kF2TD8cdo2tlw9ESYADSskFml6UALcBQNvQRwdFsAv2ypuYqE0NB5jieQR1DiGYep3fCi4QmT3aSuGIndYXD8d+iwa4tNc1nW//L2BnN1NPo3FKdTIxnW5Kl+rlCcy4ORU6jbYjT/N4kMEEziv+WEXHam88DFY0S/jq5wVPJMX6hQMo/jPCO0wRPk2jkfwFZPw90M0Wv0Yp/JASV6ByR6e2perHvyCleFRGcFZfvAIDSEeuhGRMoFxMUM6x84jqI3DkDNFoaES/L8q+NGql1zGo4Ez8EBBll4xkhF5XTRpHgP8NARPKk1CFCjjLYUCAyBsyoTVQ8h8eTU+hn8mCSjtZlxPNi0AXEHFQzTbh7M44+H5jba7WILQm0L9HUdKMbh10UraMW4w1rxbmPl25rXVNNeXFgev+Mx65wXoP+gEphP5ytXUeLl6IYgg4p39OQ60C6yflSl44UqjMjvNwK3ewtNsN7F2tG2VLaNcq0kxgFoWE0EYgH/ramg5MtOYJzXMHnZSW6K+GRFUHgZpvi8A+PUKbpRLgPTksVWNTmj8FAMBYQqEtCnpbyVicKVxfEmszU0hx02SPGCp9Vw6u1oYdHk+BVf4Aa8LHwSSxXGOlhOBsVIkqv77DbmDm0JGBUttNnQb0MH5+6NPYaoedMlxQvRAp2VGXDSVsmNlVz10OCxM8RpXclU82t0a5bY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: tunnel-credentials
      namespace: cloudflared

