apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kong

resources:
  - ../source
  # kong has namespace already declared in source
  # - namespace.yaml

patches:
  - path: timeout.yaml
    target:
      kind: CustomResourceDefinition
      name: kongingresses.configuration.konghq.com
