apiVersion: v1
kind: Service
metadata:
  name: mywebsite
spec:
  type: NodePort
  selector:
    app: mywebsite
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30000
