apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../source
  - ingress.yaml

namespace: longhorn-system

patches:
- path: number-of-replicas.yaml
  target:
    kind: ConfigMap
    name: longhorn-storageclass
