apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo-deployment
  labels:
    app: matomo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
  template:
    metadata:
      labels:
        app: matomo
    spec:
      containers:
      - name: matomo
        image: matomo
        ports:
        - containerPort: 80
      env:
      - name: MATOMO_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: password
      envFrom:
      - configMapRef:
          name: matomo-config
