apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: matomo
spec:
  encryptedData:
    password: AgCyCSL6s0xc7AILgwjcMmaKs9hXqakWcKfKJ20ksybJgaIynt/NGWuzo3wL9Mpb3gjkHDXFSY8qlhgAk1C1rHEw5GfdGTbHRzyyBfQWL8gyAsqTVcE8vz0WRWg47u6uS+Zq03R1NdugZMDTZOPrzGqlldwZfCO/r2zFPD54K5ROiBlf1XuLP3UqeWhLglMsK7H+hmQPlvTrhxNEpVy9SwLD42++ayWdCYzVOkevvH7/Y1Q03N5USa+XOI/Q0BViFlkjsWV6BV6tvySLNENeFU7QRlxKDd9M4+/bFq8rk+AVDDWi6/imb74UY6jGQpIAcH3ZCyq9mq4WDSsIBC4Y+b7/Tjp/+xGKtv5Trg7Nsq294Qyregn16WPno/ZtK+H0DlCzSJxfzX9AcVBG8736hbqaQtwdr63qncxyHYDBJTKf82r/Ln5woaoVTGdjcJ8DOBEPtIJg7ueBaLwKGim614TLqjT/BW7JlPU0YWIjTLiExAhzad82XkbzK1jP/ny1QpfvGZPmMU8TVsWCHLB2PCur4gVB+4AMGuk6FD2FBpGVmFjjKlIOTaPMZeGOhkrHGT6VdarMcqLNQe9PG7j2cTtHoFseCTW4feY4DqhKIYWPHt4KC0Jnd4URWwWYypjQ58LUBCTqdYhrJVFYimHV9nmS22HhsYdGI1LkvujXTXD6IjaH9Ty0SgFUPCkZ5CtkO/8ra32WdC7THrxVNg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: matomo
    type: kubernetes.io/basic-auth

