apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: matomo
spec:
  encryptedData:
    password: AgDW3Hci2btBlZWPlUvHz3Y7TVJEM839J3X7pFo8wFrLRxbwGfLgycHENdTfGRjm2w5FSbO+1+5bFFFoU57wFXCbSOezR4lUql7o9C4SXV4Yw5HIfQzk0gYUiaPIPDrdDC64zCa6kS5MYfgzsyqcBPxRHw+X9fWlobGek9Q4D7gxLspCQ0M1Gg5f6hhZRiPf/VhPEnq7up4C8XIwCZEb9oqHHvaszAGS0UDEnLOBxQVzSWgR30AbXlK/pvTpW8L8ic+Y5j/9nRtZRgh7N/U4OAUV5ozRFnLbbIF6DynrnLSvd082Ukme8TaKMrdoIb49ysjpGHDZ/IygrDUjTd3Z7J22RazyvlwSyKhbJpUIKQEVobowMFJAMV6uNjPuF0CRgi7g4AbzasXEedL0eYWveW0vWmCVuW+sTUw0xiBaM6mE9bF55uceyqASKg6031xzGs4BRrVOAJefEXYEnO1vdKDMYX6x0QOZoKO1kgmHYYomjGomhIgai3Hx3+wIs5kGUxu78wzJUneFBRUZojKNSMefLSr/nBVgub9SEm7aNOdIU3J/QKzlf6ZdPXVbL5dfFXaMFUsMJZseVZPQwL352OlOHBRxFl9t13O3UTplQhnziDhcfHl/rJyHwGp2OOtmkWl7uKyIido+Ca2T4WEentLm++PAh2cnbBbcmo82HMtk7/tIMmNFkXUyMOgfmFz8Jq6WTsmVs202Pgzkdw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: matomo
    type: kubernetes.io/basic-auth

