apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: matomo
spec:
  encryptedData:
    password: AgAioVQwfTL/oDmc9JneEFcKv+EIUCV3/I4pvTJivx0Kk4VQRhTUrZkkTnNlmQVnXzLVfy4EGOlyFmcaCPKXy9ImOzWv0TB9bl9C9FYSQSJvZJCTWGjRp42giBPrtLXiZiFhc0VQd2V8HzgYFdkU0xlTfTLmhmUMNhAf6XiWjApu0XJwSuFEyYrbFcJXwBR58BHPoJE10qFLsi9MDpLUwRsbcgGsKgM1twTY0n2lW7myShbNDC7/cGwNMAiipLNuwWtTz+HEln7v/V8mAHGSF0kI7mLEmj1hx+VabqbI6lifU62cXOOVjOX/7L1omiJTcQ9l+FL5Px/bFG0wbke6mD0o33h/7rh6vGs7ALtyCVo+eiyxt9BFbUWUy9Di0JyvigpGZWmCe3ixLTXFz+O3Fvxkr/d6jUSzbWs9XKxRmXa634WJiy+XfkjEDF39iigWxYyz3Dx3topVZHsbqNvHDzS0Q5cWM7g2rT8S/UE00KiYeSmhY00gZOijdzbYE93k5mlGtr8bqnb7GUAOm3xgMjUZbJnu5d8JtsGhi29MJVTgOpBF7MljPTXHg+UVoOqJOeY6aJE1bI4Jfoptyyaze+moWOKxS5ZurJh97A1eauQ9EOfnbHcmK7kcLUJlLPm5ZMjKovFfljQes2KaUMBuzbZ8fqX66WcO1nZy44iOc0yd0r74Kol/8WswmN4F6Hqzgwzs5766pOJ16IZXXA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: matomo
    type: kubernetes.io/basic-auth

