apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inlets-helm-patches
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.gitopsrepo }}
    targetRevision: HEAD
    path: applications/inlets/helm-patches
  destination:
    server: https://kubernetes.default.svc
    namespace: inlets

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
